/** Resolution reads package metadata without importing any project or driver. */
import {readFile,realpath,lstat,access} from 'node:fs/promises';
import {join,dirname,resolve,sep,delimiter} from 'node:path';
import {createRequire} from 'node:module';
import {config,boundary,literalDirectory,literalFile,safeRelative,ROOT} from './integrity.mjs';
import {runBounded,completed} from './runner.mjs';
export const REQUIRED_NODE='v24.21.0',REQUIRED_NPM='11.19.0';
export async function findNpmCli(){const directories=[dirname(process.execPath),...(process.env.PATH||'').split(delimiter).filter(Boolean)],candidates=[];for(const directory of directories){candidates.push(join(directory,'node_modules/npm/bin/npm-cli.js'),resolve(directory,'../lib/node_modules/npm/bin/npm-cli.js'));for(const name of ['npm','npm.cmd'])try{const path=await realpath(join(directory,name));if(path.endsWith('npm-cli.js'))candidates.push(path);else candidates.push(join(dirname(path),'node_modules/npm/bin/npm-cli.js'));}catch{}}for(const path of new Set(candidates))try{await access(path);return path;}catch{}return null;}
export function dependencyRecord({name,expected,actual,resolved,localRoot,linked=false}){const errors=[];if(!expected)errors.push('LOCK_ENTRY_MISSING');if(!resolved||!resolved.startsWith(resolve(localRoot)+sep))errors.push('NOT_PROJECT_LOCAL');if(linked)errors.push('LINKED_DEPENDENCY_PATH');if(actual!==expected)errors.push('LOCK_VERSION_MISMATCH');return {name,expected:expected??null,actual:actual??null,resolved:resolved??null,errors};}
export async function preflight(id='p02',{root=ROOT}={}){const contract=await config(id,root),directory=join(root,contract.root),source=await boundary(id,root);let pkg={},lock={},sourceError=null;try{await literalDirectory(directory);const packagePath=await literalFile(join(directory,'package.json')),lockPath=await literalFile(join(directory,'package-lock.json'));pkg=JSON.parse(await readFile(packagePath,'utf8'));lock=JSON.parse(await readFile(lockPath,'utf8'));}catch(error){sourceError=error.code||error.message;}const npmCli=await findNpmCli(),npmResult=npmCli?await runBounded(process.execPath,[npmCli,'--version'],{timeout:5000,maxBytes:65536}):null;const npm=npmResult&&completed(npmResult)&&/^\d+\.\d+\.\d+\n?$/.test(npmResult.stdout)?npmResult.stdout.trim():null,dependencies=[];for(const name of Object.keys(pkg.dependencies||{})){let actual=null,resolved=null,linked=false,error=null;try{if(!safeRelative('node_modules/'+name+'/package.json'))throw Error('UNSAFE_DEPENDENCY_PATH');const localMetadata=join(directory,'node_modules',name,'package.json');await literalDirectory(dirname(localMetadata));linked=(await lstat(localMetadata)).isSymbolicLink();await literalFile(localMetadata);const request=createRequire(join(directory,'package.json'));resolved=request.resolve(name+'/package.json');if(resolve(resolved)!==resolve(localMetadata))throw Error('NOT_LITERAL_PROJECT_LOCAL_METADATA');await literalFile(resolved);actual=JSON.parse(await readFile(resolved,'utf8')).version;}catch(caught){error=caught.code||caught.message;}const record=dependencyRecord({name,expected:lock.packages?.['node_modules/'+name]?.version,actual,resolved,localRoot:join(directory,'node_modules'),linked});if(error)record.errors.unshift(error);dependencies.push(record);}const versionsMatch=process.version===REQUIRED_NODE&&npm===REQUIRED_NPM,resolutionReady=!sourceError&&dependencies.length>0&&dependencies.every(record=>record.errors.length===0);return {project:id,role:contract.role,node:process.version,npm,requiredNode:REQUIRED_NODE,requiredNpm:REQUIRED_NPM,versionsMatch,source,sourceError,dependencies,resolutionReady,ready:versionsMatch&&source.ok&&resolutionReady,npmMeasurement:{command:npmResult?.command??null,args:npmResult?.args??null,stderr:npmResult?.stderr??'',fault:npmResult?.spawnError??(npmResult?.timedOut?'TIMEOUT':npmResult?.overflow?'OUTPUT_BOUND':npmResult?.signal?'SIGNAL':npmResult?.controllerFallback?'CONTROLLER_FALLBACK':null)},native:{attempted:false,status:'NOT_LOADED'},qualification:'SOURCE_RESOLUTION_ONLY_NOT_NATIVE_QUALIFICATION',limitations:['Direct dependency metadata only; no complete graph or publisher provenance authentication.','No project, canonical helper, test or native driver is imported by preflight.','No installation or module substitution is performed.']};}
export function requireReady(info){if(!info.ready)throw Error('ENVIRONMENT_BLOCKED: record measured versions, boundary and local dependency errors. Use the separately prepared teaching environment; this tool does not install dependencies.');return info;}
