/** New S07 derived tooling. Byte boundaries are not signatures or an execution sandbox. */
import {readFile,readdir,lstat,realpath} from 'node:fs/promises';
import {join,resolve,dirname,parse,relative} from 'node:path';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
export const ROOT=resolve(dirname(fileURLToPath(import.meta.url)),'..');
export const sha=data=>createHash('sha256').update(data).digest('hex');
export function safeRelative(value){return typeof value==='string'&&value.length>0&&!/[\\:?*<>"|\x00-\x1f\x7f]/.test(value)&&!value.startsWith('/')&&value.split('/').every(part=>part&&part!=='.'&&part!=='..'&&!/[. ]$/.test(part)&&!/^(?:CON|PRN|AUX|NUL|CONIN\$|CONOUT\$|COM[1-9¹²³]|LPT[1-9¹²³])(?:\.|$)/i.test(part));}
/** Check every directory ancestor, including package and project parents. */
export async function literalDirectory(directory){const absolute=resolve(directory),base=parse(absolute).root;let cursor=base;for(const part of relative(base,absolute).split(/[\\/]/).filter(Boolean)){cursor=join(cursor,part);const stat=await lstat(cursor);if(stat.isSymbolicLink()||!stat.isDirectory())throw Error('Linked or non-directory ancestor: '+cursor);}if(await realpath(absolute)!==absolute)throw Error('Directory resolution differs from literal path');return absolute;}
/** Reject linked metadata before reading it; this does not remove filesystem race risks. */
export async function literalFile(path){const absolute=resolve(path),stat=await lstat(absolute);if(stat.isSymbolicLink()||!stat.isFile()||await realpath(absolute)!==absolute)throw Error('Linked or nonregular file: '+absolute);return absolute;}
export async function config(id,root=ROOT){await literalDirectory(root);await literalDirectory(join(root,'tools'));const contractPath=await literalFile(join(root,'tools/PROJECT_CONTRACT.json')),all=JSON.parse(await readFile(contractPath,'utf8'));if(all?.schema!=='tw2026.s07.derived-tool-contract.v1'||!['STUDENT','PRIVATE_REFERENCE'].includes(all.role)||!all.projects||typeof all.projects!=='object'||Array.isArray(all.projects))throw Error('Invalid project contract role or schema');if(!['p01','p02','p03'].includes(id)||!Object.hasOwn(all.projects,id))throw Error('Unknown project; use p02, p01 or p03');const value=all.projects[id],expectedRoot=all.role==='STUDENT'?(id==='p02'?'02_PROJECTS/p02':'02_PROJECTS/optional/'+id):'06_REFERENCE/'+id,expectedTarget=all.role==='STUDENT'&&id==='p02'?'src/book-seats.js':null;if(!value||value.role!==all.role||value.root!==expectedRoot||value.target!==expectedTarget||!value.files||typeof value.files!=='object'||Array.isArray(value.files)||!Object.keys(value.files).length||Object.keys(value.files).some(path=>!safeRelative(path)||typeof value.files[path]!=='string'||!/^[a-f0-9]{64}$/.test(value.files[path]))||expectedTarget&&!Object.hasOwn(value.files,expectedTarget))throw Error('Invalid project contract boundary');return {...value,role:all.role};}
async function walk(directory,{skipDependencies=false}={}){const files=[],errors=[];async function visit(dir,prefix=''){for(const entry of await readdir(dir,{withFileTypes:true})){const name=prefix?prefix+'/'+entry.name:entry.name,path=join(dir,entry.name);if(entry.isSymbolicLink()){errors.push('Symlink '+name);continue;}if(skipDependencies&&!prefix&&entry.name==='node_modules'){if(!entry.isDirectory())errors.push('Invalid node_modules');continue;}if(!safeRelative(name)){errors.push('Unsafe path '+name);continue;}if(entry.isDirectory())await visit(path,name);else if(entry.isFile())files.push(name);else errors.push('Nonregular '+name);}}try{await literalDirectory(directory);await visit(directory);}catch(error){errors.push('Unreadable directory: '+error.message);}return {files:files.sort(),errors};}
export async function boundary(id='p02',root=ROOT){let contract;try{contract=await config(id,root);}catch(error){return {project:id,role:null,ok:false,status:'FAIL_CLOSED',errors:['Invalid or unreadable project contract: '+error.message],files:0,allowedTarget:null,targetSha256:null,untouched:null,scope:'PROTECTED_BYTES_FROM_SUPPLIED_CONTRACT_NOT_SEMANTIC_REVIEW_OR_SIGNATURE'};}const directory=join(root,contract.root),found=await walk(directory,{skipDependencies:true}),errors=[...found.errors];let targetSha256=null;for(const name of found.files){if(!Object.hasOwn(contract.files,name)){errors.push('Extra '+name);continue;}try{const hash=sha(await readFile(join(directory,name)));if(name===contract.target)targetSha256=hash;else if(hash!==contract.files[name])errors.push('Changed '+name);}catch(error){errors.push('Unreadable '+name+': '+error.code);}}for(const name of Object.keys(contract.files))if(!found.files.includes(name))errors.push('Missing '+name);return {project:id,role:contract.role,ok:errors.length===0,status:errors.length?'FAIL_CLOSED':'PASS_PROTECTED_BOUNDARY',errors,files:found.files.length,allowedTarget:contract.target??null,targetSha256,untouched:contract.target?targetSha256===contract.files[contract.target]:null,scope:'PROTECTED_BYTES_FROM_SUPPLIED_CONTRACT_NOT_SEMANTIC_REVIEW_OR_SIGNATURE'};}
export async function verifyPackage(root=ROOT){let manifest,pid;try{await literalDirectory(root);manifest=await readFile(await literalFile(join(root,'SHA256SUMS.txt')));pid=await readFile(await literalFile(join(root,'PACKAGE_ID.txt')),'utf8');}catch(error){return {ok:false,status:'BLOCKED',errors:['Package identity unreadable: '+error.message]};}const errors=[],text=manifest.toString('utf8'),rows=[],seen=new Set(),folded=new Map();if(!text.endsWith('\n')||text.includes('\r')||!Buffer.from(text).equals(manifest))errors.push('Manifest must be exact UTF-8 with LF and final newline');for(const line of text.split('\n').slice(0,-1)){const match=line.match(/^([a-f0-9]{64})  (.+)$/);if(!match||!safeRelative(match?.[2])||['SHA256SUMS.txt','PACKAGE_ID.txt'].includes(match?.[2])){errors.push('Malformed or unsafe row');continue;}const name=match[2];if(seen.has(name))errors.push('Duplicate '+name);seen.add(name);const parts=name.split('/');for(let n=1;n<=parts.length;n++){const literal=parts.slice(0,n).join('/'),key=literal.normalize('NFC').toLowerCase();if(folded.has(key)&&folded.get(key)!==literal)errors.push('Case/Unicode collision '+literal);folded.set(key,literal);}rows.push({name,hash:match[1]});}if(rows.map(row=>row.name).join('\n')!==rows.map(row=>row.name).sort().join('\n'))errors.push('Manifest path order differs');if(!/^[a-f0-9]{64}\n$/.test(pid)||pid.trim()!==sha(manifest))errors.push('PACKAGE_ID must hash exact manifest bytes');const found=await walk(root),expected=[...seen,'SHA256SUMS.txt','PACKAGE_ID.txt'].sort();errors.push(...found.errors);for(const name of expected)if(!found.files.includes(name))errors.push('Missing '+name);for(const name of found.files)if(!expected.includes(name))errors.push('Extra '+name);for(const row of rows)if(found.files.includes(row.name)&&sha(await readFile(join(root,row.name)))!==row.hash)errors.push('Hash mismatch '+row.name);return {ok:errors.length===0,status:errors.length?'FAIL_CLOSED':'PASS_EXACT_PACKAGE_BYTES',files:rows.length,packageId:pid.trim(),errors,scope:'CLEAN_EXTRACTED_PACKAGE_ONLY_BEFORE_EDITING_OR_DEPENDENCY_PREPARATION',limitation:'Byte identity is not evidence authentication, a signature or native qualification.'};}
