/** Option-identity observer. It observes supplied calls and never repairs the service. */
export const FIVE_OPERATIONS=['Event.findByPk','Booking.findOne','event.save','Booking.create','BookingAudit.create'];
export function assessTrace({operations,transactions,callbackTransactions=[]}){const problems=[];if(transactions.length!==1||transactions[0]===null||transactions[0]===undefined)problems.push('Expected exactly one non-null managed transaction');if(operations.length!==5||operations.map(item=>item.operation).join('|')!==FIVE_OPERATIONS.join('|'))problems.push('Expected each of the five named operations once in source order');const managed=transactions[0];if(operations.some(item=>item.transaction===null||item.transaction===undefined||item.transaction!==managed))problems.push('Every operation must explicitly receive the same non-null managed transaction');if(callbackTransactions.length!==1||callbackTransactions[0]===null||callbackTransactions[0]===undefined||callbackTransactions[0]!==managed)problems.push('Callback transaction must be the same non-null managed identity');return {ok:problems.length===0,problems};}
export async function observeBooking(database,book,request){const operations=[],transactions=[],callbackTransactions=[],events=[],undo=[],instances=new WeakSet();const replace=(target,name,wrapper)=>{const descriptor=Object.getOwnPropertyDescriptor(target,name),original=target[name];if(typeof original!=='function'||descriptor&&(!Object.hasOwn(descriptor,'value')))throw Error('Observer requires replaceable method '+name);Object.defineProperty(target,name,descriptor?{...descriptor,value:wrapper(original)}:{value:wrapper(original),writable:true,configurable:true,enumerable:true});undo.push(()=>{if(descriptor)Object.defineProperty(target,name,descriptor);else delete target[name];});};let result,error=null,failed=false;
 try{replace(database.sequelize,'transaction',original=>async function(...args){const last=args.length-1;if(typeof args[last]!=='function')throw Error('Observer supports one managed callback transaction only');const callback=args[last];args[last]=async transaction=>{transactions.push(transaction);events.push('managed callback entered');const value=await callback(transaction);events.push('managed callback fulfilled');return value;};const value=await original.apply(this,args);events.push('managed transaction promise fulfilled');return value;});
 replace(database.Event,'findByPk',original=>async function(...args){operations.push({operation:'Event.findByPk',transaction:args.at(-1)?.transaction});const event=await original.apply(this,args);if(event&&!instances.has(event)){instances.add(event);replace(event,'save',saved=>async function(...saveArgs){operations.push({operation:'event.save',transaction:saveArgs.at(-1)?.transaction});return saved.apply(this,saveArgs);});}return event;});
 for(const [target,name,label] of [[database.Booking,'findOne','Booking.findOne'],[database.Booking,'create','Booking.create'],[database.BookingAudit,'create','BookingAudit.create']])replace(target,name,original=>async function(...args){operations.push({operation:label,transaction:args.at(-1)?.transaction});return original.apply(this,args);});
 const callback=request.afterBookingCreated??(async()=>{});result=await book(database,{...request,afterBookingCreated:async info=>{callbackTransactions.push(info?.transaction);events.push('afterBookingCreated entered');return callback(info);}});events.push('outer book promise fulfilled');
 }catch(caught){error=caught;failed=true;events.push('outer book promise rejected');}finally{for(const restore of undo.reverse())restore();}
 const identity=value=>value===undefined?'UNDEFINED':value===null?'NULL':transactions.includes(value)?'MANAGED_'+(transactions.indexOf(value)+1):'OTHER_IDENTITY';const assessment=assessTrace({operations,transactions,callbackTransactions});return {result,error,report:{outcome:failed?'REJECTED':'FULFILLED',error:failed?(error instanceof Error?{name:error.name,code:error.code??null,message:error.message}:{name:'NonErrorThrownValue',code:null,message:String(error),thrownType:error===null?'null':typeof error}):null,managedTransactions:transactions.length,operations:operations.map(item=>({operation:item.operation,transactionIdentity:identity(item.transaction),explicitNonNull:item.transaction!==null&&item.transaction!==undefined})),callbackTransactions:callbackTransactions.map(identity),events,fiveOperationWitness:assessment,scope:'OBSERVED_OPTIONS_AND_PROMISE_ORDER_NOT_SQL_COMMIT_TRACE_OR_CONCURRENCY_QUALIFICATION'}};
}
