/** Canonical imports occur only inside explicitly selected, strictly gated functions. */
import {join} from 'node:path';
import {pathToFileURL} from 'node:url';
import {createRequire} from 'node:module';
import {isDeepStrictEqual} from 'node:util';
import {config,ROOT} from './integrity.mjs';
import {preflight,requireReady} from './environment.mjs';
import {createOwnedApi,withDatabase} from './lifecycle.mjs';
import {observeBooking} from './observer.mjs';
import {runBounded,completed} from './runner.mjs';
export async function loadNative(id='p02',{root=ROOT}={}){const info=requireReady(await preflight(id,{root})),contract=await config(id,root),directory=join(root,contract.root);if(id==='p03')return {project:id,status:'SQLITE_NOT_APPLICABLE',databaseOpened:false,info};const request=createRequire(join(directory,'package.json'));request('sqlite3');return {project:id,status:'NATIVE_SQLITE3_MODULE_LOADED',databaseOpened:false,info,qualification:'MODULE_LOAD_ONLY_NOT_ORM_SQL_ROLLBACK_OR_PROVENANCE_QUALIFICATION'};}
async function modules(id,root){await loadNative(id,{root});const contract=await config(id,root),directory=join(root,contract.root),load=name=>import(pathToFileURL(join(directory,'src',name)).href);if(id==='p03'){const [{createApp},{createRegistrationService}]=await Promise.all([load('app.js'),load('registration-service.js')]);return {createApp,appArguments:()=>({service:createRegistrationService()}),directory,load,role:contract.role};}const [{createApp},{createDatabase,initializeDatabase}]=await Promise.all([load('app.js'),load('database.js')]);return {createApp,createDatabase,initializeDatabase,appArguments:database=>id==='p01'?{models:database.models}:{database},directory,load,role:contract.role};}
export async function serve(id='p02',{root=ROOT,allowMemory=false,port=0}={}){if(!allowMemory)throw Error('MEMORY_CONSENT_REQUIRED: pass --allow-memory-database to acknowledge a fresh volatile fixture every start.');const loaded=await modules(id,root);return createOwnedApi(loaded,port);}
const state=async database=>{const event=await database.Event.findByPk(1);return {availableSeats:event?.availableSeats??null,bookings:await database.Booking.count(),audits:await database.BookingAudit.count()};};
export async function observeP02({root=ROOT,allowMemory=false}={}){if(!allowMemory)throw Error('MEMORY_CONSENT_REQUIRED');const loaded=await modules('p02',root),[{bookSeats},{unsafeBookSeats}]=await Promise.all([loaded.load('book-seats.js'),loaded.load('unsafe-book-seats.js')]),scenarios=[];
 const run=async(id,title,book,request,expected,{auditFailure=false,recover=false}={})=>withDatabase(loaded,async database=>{const before=await state(database),sentinel=Error(id+'_CONTROLLED_FAILURE'),originalAudit=database.BookingAudit.create;if(auditFailure)database.BookingAudit.create=async()=>{throw sentinel;};let observed;try{observed=await observeBooking(database,book,{eventId:1,attendeeId:10,seats:2,...request,afterBookingCreated:request?.failCallback?async()=>{throw sentinel;}:async()=>{}});}finally{database.BookingAudit.create=originalAudit;}const after=await state(database),row={id,title,fixture:{eventId:1,seed:'Web Systems/capacity5/available5/bookings0/audits0',instance:id},request:{eventId:1,attendeeId:10,seats:2,...request},evidenceClass:'GENUINE_ORM_SQLITE',before,after,sourceExpected:expected,stateMatchesSourceExpectation:isDeepStrictEqual(after,expected),controlledErrorIdentity:request?.failCallback||auditFailure?observed.error===sentinel:null,...observed.report};if(recover){const recoveryBefore=await state(database),next=await observeBooking(database,bookSeats,{eventId:1,attendeeId:20,seats:1});row.recovery={sameInstance:true,request:{eventId:1,attendeeId:20,seats:1},before:recoveryBefore,after:await state(database),sourceExpected:{availableSeats:4,bookings:1,audits:1},...next.report};row.recovery.stateMatchesSourceExpectation=isDeepStrictEqual(row.recovery.after,row.recovery.sourceExpected);}scenarios.push(row);});
 await run('E01','Unsafe callback failure',unsafeBookSeats,{failCallback:true},{availableSeats:3,bookings:1,audits:0});
 await run('E02_SERVICE','Managed success and five-operation witness',bookSeats,{}, {availableSeats:3,bookings:1,audits:1});
 await run('E03_CALLBACK','Managed callback failure and same-instance recovery',bookSeats,{failCallback:true},{availableSeats:5,bookings:0,audits:0},{recover:true});
 await run('E03_AUDIT','Audit failure before insert and same-instance recovery',bookSeats,{}, {availableSeats:5,bookings:0,audits:0},{auditFailure:true,recover:true});
 await run('E04_INVALID','Invalid seats reject unchanged',bookSeats,{seats:0},{availableSeats:5,bookings:0,audits:0});
 await run('E04_MISSING','Missing event rejects unchanged',bookSeats,{eventId:99},{availableSeats:5,bookings:0,audits:0});
 await run('E04_SOLD_OUT','Insufficient stock rejects unchanged',bookSeats,{seats:6},{availableSeats:5,bookings:0,audits:0});
 await run('E04_LAST_SEAT','Last permitted stock boundary',bookSeats,{seats:5},{availableSeats:0,bookings:1,audits:1});
 await withDatabase(loaded,async database=>{await bookSeats(database,{eventId:1,attendeeId:10,seats:4});const before=await state(database),duplicate=await observeBooking(database,bookSeats,{eventId:1,attendeeId:10,seats:1}),afterDuplicate=await state(database),capacity=await observeBooking(database,bookSeats,{eventId:1,attendeeId:10,seats:2});scenarios.push({id:'E04_PRECEDENCE',evidenceClass:'GENUINE_ORM_SQLITE',fixture:{instance:'E04_PRECEDENCE',seed:'fresh5 then a successful4-seat reservation'},before,afterDuplicate,after:await state(database),duplicate:duplicate.report,capacity:capacity.report,sourceExpected:{duplicateCode:'booking_exists',capacityCode:'sold_out',state:before},limitation:'POST is not an idempotent replay; capacity precedes duplicate lookup in the supplied reference.'});});
 const api=await createOwnedApi(loaded);try{const before=await state(api.database),path='/api/events/1/bookings',request={attendeeId:11,seats:2},response=await fetch(api.origin+path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(request),signal:AbortSignal.timeout(5000)}),body=await response.json(),after=await state(api.database);scenarios.push({id:'E02_HTTP',evidenceClass:'LOCAL_HTTP',fixture:{instance:'E02_HTTP',seed:'fresh5/0/0'},origin:api.origin,path,method:'POST',request,status:response.status,location:response.headers.get('location'),body,before,after,sourceExpected:{status:201,location:'/api/bookings/1',state:{availableSeats:3,bookings:1,audits:1}},limitation:'Location is observed response metadata; no GET booking-member route is supplied.'});}finally{await api.close();}
 return {project:'p02',role:loaded.role,evidenceClasses:['GENUINE_ORM_SQLITE','LOCAL_HTTP'],execution:'ACTUALLY_EXECUTED_BY_THIS_INVOCATION',scenarios,limitations:['Sequential observations only; no isolation, concurrency, crash durability or external-effect rollback qualification.','The observer records explicit option identity rather than proving a complete native transaction graph.','Audit failure is injected before insert and cannot establish an escaped audit row.','UniqueConstraintError class translation can include callback or audit origin.','Unexpected failures abort this report; an incomplete report is not a pass.']};}
export async function canonicalTests(id='p02',{root=ROOT,allowMemory=false}={}){if(!allowMemory)throw Error('MEMORY_CONSENT_REQUIRED');await loadNative(id,{root});const contract=await config(id,root),directory=join(root,contract.root),files=['baseline.test.js','objective.test.js','regression.test.js'].map(name=>join(directory,'tests',name)),result=await runBounded(process.execPath,['--test','--test-reporter=tap',...files],{cwd:directory,timeout:60000,maxBytes:2_000_000});return {project:id,role:contract.role,evidenceClass:id==='p03'?'LOCAL_HTTP':'GENUINE_ORM_SQLITE',execution:'ACTUALLY_EXECUTED_BY_THIS_INVOCATION',status:completed(result)?'CHILD_EXIT_ZERO_REVIEW_COMPLETE_TAP':'FAIL_OR_EXECUTION_FAULT',result,limitation:'Review the complete TAP output and named cases. Exit status alone is not an evidence-authenticity check. Canonical helper setup/cleanup limits remain unchanged; forced termination leaves cleanup unknown.'};}
