[CmdletBinding()]
param()
$ErrorActionPreference='Stop';[Console]::OutputEncoding=New-Object System.Text.UTF8Encoding($false)
$Root=(Resolve-Path -LiteralPath (Split-Path -Parent $PSScriptRoot)).Path.TrimEnd('\');$Verify=Join-Path $PSScriptRoot 'VERIFY_STUDENT_PACKAGE.ps1';$Stop=Join-Path $PSScriptRoot 'STOP_PROJECT.ps1';$Project=Join-Path $Root '01_PROIECT\RESPONSIVE_CARD_GRID_CANONIC';$Wrapper=Join-Path $Root '01_PROIECT\run-student-grid.mjs';$Offline=Join-Path $Root '02_LABORATOR_OFFLINE\OFFLINE_VIEWPORT_LAB_v2.1_EN_GB.html';$Id=(Get-Content -LiteralPath (Join-Path $Root '05_AUDIT\PACKAGE_ID.txt') -Raw).Trim();$Runtime=Join-Path $env:TEMP ('TW_S02_'+$Id.Substring(0,16));$Control=Join-Path $Runtime 'control.json';$Ready=Join-Path $Runtime 'ready.json'
function Pass($t){Write-Host "PASS  $t" -ForegroundColor Green}function Warn($t){Write-Host "WARN  $t" -ForegroundColor Yellow}function StopNow($t){Write-Host "STOP  $t" -ForegroundColor Red;[void](Read-Host 'ENTER');exit 2}
& $Verify -Quiet -AllowStudentWork;if($LASTEXITCODE -ne 0){StopNow 'Immutable package files failed verification.'};Pass 'Immutable package set PASS.';New-Item -ItemType Directory -Path $Runtime -Force|Out-Null;& powershell.exe -NoProfile -ExecutionPolicy Bypass -File $Stop -NonInteractive|Out-Null
$Node=Get-Command node -ErrorAction SilentlyContinue
if($null -eq $Node){Warn 'Node/npm exact runtime unavailable; opening offline laboratory.';Start-Process ([Uri](Resolve-Path -LiteralPath $Offline).Path).AbsoluteUri|Out-Null;exit 2}
$NodeVersion=(& $Node.Source --version|Select-Object -First 1).Trim()
$Npm=Get-Command npm.cmd -ErrorAction SilentlyContinue;if($null -eq $Npm){$Npm=Get-Command npm -ErrorAction SilentlyContinue}
$NpmVersion=if($null -ne $Npm){(& $Npm.Source --version|Select-Object -First 1).Trim()}else{''}
if($NodeVersion -ne 'v24.21.0' -or $NpmVersion -ne '11.19.0'){Warn 'Node/npm exact runtime unavailable; opening offline laboratory.';Start-Process ([Uri](Resolve-Path -LiteralPath $Offline).Path).AbsoluteUri|Out-Null;exit 2}
$token=[Guid]::NewGuid().ToString();$args=@(('"{0}"' -f $Wrapper),'--project',('"{0}"' -f $Project),'--runtime',('"{0}"' -f $Runtime),'--token',$token)-join ' ';$p=Start-Process -FilePath $Node.Source -ArgumentList $args -PassThru -WindowStyle Hidden;$c=[ordered]@{pid="$($p.Id)";nodePath=[IO.Path]::GetFullPath($Node.Source);wrapper=[IO.Path]::GetFullPath($Wrapper);token=$token};$c|ConvertTo-Json|Set-Content -LiteralPath $Control -Encoding UTF8;$deadline=(Get-Date).AddSeconds(12);$url='';while((Get-Date)-lt $deadline){if($p.HasExited){break};if(Test-Path -LiteralPath $Ready){try{$r=Get-Content -LiteralPath $Ready -Raw|ConvertFrom-Json;if($r.token -eq $token -and $r.url -match '^http://127\.0\.0\.1:\d+$'){$url=[string]$r.url;break}}catch{}};Start-Sleep -Milliseconds 200};if(-not $url){& powershell.exe -NoProfile -ExecutionPolicy Bypass -File $Stop -NonInteractive|Out-Null;Warn 'Live project unavailable; opening offline laboratory.';Start-Process ([Uri](Resolve-Path -LiteralPath $Offline).Path).AbsoluteUri|Out-Null;exit 0};Start-Process $url|Out-Null;Pass "Project: $url";Write-Host 'Edit only public\styles.css. Return here at the end.';[void](Read-Host 'ENTER for cleanup');& powershell.exe -NoProfile -ExecutionPolicy Bypass -File $Stop -NonInteractive;exit $LASTEXITCODE
