import assert from "node:assert/strict";
import test from "node:test";
import { createWorkerClient } from "../src/worker-client.js";
import { createFakeWorker } from "./fake-worker.mjs";

const code = async (promise) => { try { await promise; return null; } catch (error) { return error.code; } };
const fixture = (options = {}) => { let sequence = 0; const workers = []; const createWorker = () => { const worker = options.createWorker?.() ?? createFakeWorker(options.workerOptions); workers.push(worker); return worker; }; return { workers, client: createWorkerClient({ createWorker, nextId: options.nextId ?? (() => `r${++sequence}`) }) }; };

test("validation and pre-abort avoid worker creation while send is pre-registered", async () => { const f = fixture(); assert.equal(await code(f.client.analyze([])), "invalid_values"); const controller = new AbortController(); controller.abort(); assert.equal(await code(f.client.analyze([1], { signal: controller.signal })), "analysis_aborted"); assert.equal(f.workers.length, 0); const synchronous = fixture({ workerOptions: { onPost(message, worker) { worker.emit("message", { type: "analysis.completed", requestId: message.requestId, result: { ok: true } }); } } }); assert.deepEqual(await synchronous.client.analyze([1, 2]), { ok: true }); assert.deepEqual(synchronous.workers[0].sent()[0], { type: "analysis.start", requestId: "r1", values: [1, 2] }); synchronous.client.dispose(); });
test("concurrent out-of-order results and monotonic progress correlate", async () => { const f = fixture(); const progress = []; const one = f.client.analyze([1], { onProgress: (value) => progress.push(value) }); const two = f.client.analyze([2]); one.catch(() => {}); two.catch(() => {}); assert.equal(f.workers.length, 1); const worker = f.workers[0]; worker.emit("message", { type: "analysis.progress", requestId: "r1", progress: 40 }); worker.emit("message", { type: "analysis.progress", requestId: "r1", progress: 20 }); worker.emit("message", { type: "analysis.completed", requestId: "r2", result: "two" }); worker.emit("message", { type: "analysis.completed", requestId: "r1", result: "one" }); assert.deepEqual(await Promise.all([one, two]), ["one", "two"]); assert.deepEqual(progress, [40]); assert.equal(f.client.diagnostics.pendingCount, 0); f.client.dispose(); });
test("abort sends cancel once and ignores a late result", async () => { const f = fixture(); const controller = new AbortController(); const promise = f.client.analyze([1, 2], { signal: controller.signal }); controller.abort(); assert.equal(await code(promise), "analysis_aborted"); assert.deepEqual(f.workers[0].sent().at(-1), { type: "analysis.cancel", requestId: "r1" }); f.workers[0].emit("message", { type: "analysis.completed", requestId: "r1", result: "late" }); assert.equal(f.client.diagnostics.pendingCount, 0); f.client.dispose(); });
test("worker errors reject all safely and later instances remain isolated", async () => { const f = fixture(); const one = f.client.analyze([1]); const two = f.client.analyze([2]); one.catch(() => {}); two.catch(() => {}); assert.equal(f.workers.length, 1); f.workers[0].emit("error", new Error("worker stack secret")); assert.deepEqual(await Promise.all([code(one), code(two)]), ["worker_failed", "worker_failed"]); assert.equal(f.client.diagnostics.pendingCount, 0); const other = fixture(); assert.equal(other.client.diagnostics.hasWorker, false); f.client.dispose(); other.client.dispose(); });
test("disposal terminates, removes listeners, rejects pending, and is idempotent", async () => { const f = fixture(); const pending = f.client.analyze([1]); const worker = f.workers[0]; f.client.dispose(); assert.equal(await code(pending), "worker_client_disposed"); assert.deepEqual(worker.diagnostics(), { terminated: true, listeners: { message: 0, error: 0, messageerror: 0 } }); assert.equal(await code(f.client.analyze([1])), "worker_client_disposed"); f.client.dispose(); });
