#!/usr/bin/env python3
"""Generate a download landing page with a deliberately bounded public payload."""
from __future__ import annotations

import argparse
import html
import json
import shutil
from pathlib import Path
from urllib.parse import quote

from release_contract import ROOT, read_plan, repo_path, selection, sha, state, validate_week


MARKER = '.webtech-pages-generated'


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument('--output', type=Path, default=ROOT / '_site')
    parser.add_argument('--weeks', help='Comma-separated planned weeks; default: every planned week')
    parser.add_argument('--language', help='Select one declared language; default: all declared languages')
    parser.add_argument('--source-ref', default='main', help='GitHub tree ref for documentation links')
    args = parser.parse_args()
    out = args.output.resolve()
    try:
        if out == ROOT or out in ROOT.parents or (ROOT / '01_WEEKS') in out.parents or (ROOT / '00_TOOLS') in out.parents:
            raise ValueError('Output must not overwrite the repository or source directories')
        if out.exists():
            if not out.is_dir() or (any(out.iterdir()) and not (out / MARKER).is_file()):
                raise ValueError('Refusing to replace a non-empty folder not created by this builder')
            shutil.rmtree(out)
        plan = read_plan()
        choices = list(selection(plan, args.weeks, args.language))
        for week, _, entry, _ in choices:
            validate_week(plan, week, entry)
        out.mkdir(parents=True)
        (out / MARKER).write_text('Generated by build_pages_site.py\n', encoding='utf-8')
        shutil.copytree(ROOT / 'assets', out / 'assets')
        records = []
        rows = []
        copied = set()

        def copy_download(relative: str):
            source = repo_path(relative)
            if not source.is_file():
                raise ValueError(f'Missing download: {relative}')
            target = out / relative
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(source, target)
            side = Path(str(source) + '.sha256')
            if not side.is_file() or side.read_text(encoding='utf-8').strip() != f'{sha(source)}  {source.name}':
                raise ValueError(f'Missing or invalid sidecar: {relative}')
            shutil.copy2(side, Path(str(target) + '.sha256'))
            if relative not in copied:
                records.append({'path': relative, 'bytes': target.stat().st_size, 'sha256': sha(target)})
                copied.add(relative)

        github = 'https://github.com/antonioclim/WebTech_ASE/tree/' + quote(args.source_ref, safe='') + '/'
        for week, language, entry, item in choices:
            copy_download(item['bundle'])
            archive_href = quote(item['bundle'], safe='/')
            qualification = state(plan, entry)
            rows.append('<tr><th scope="row">Week ' + html.escape(week) + '</th><td>' + html.escape(language) + '</td><td>'
                        + html.escape(entry['version']) + '</td><td>' + html.escape(str(qualification['status']))
                        + '</td><td><a href="' + archive_href + '">Download weekly ZIP</a> · <a href="' + archive_href
                        + '.sha256">SHA-256</a> · <a href="' + github + '01_WEEKS/WEEK_' + week + '/">Read instructions on GitHub</a></td></tr>')
        setup_rows = []
        for platform in ('WINDOWS', 'MACOS_LINUX'):
            for source in sorted((ROOT / '00_SETUP' / platform / 'DOWNLOAD').glob('*.zip')):
                relative = source.relative_to(ROOT).as_posix()
                copy_download(relative)
                setup_rows.append('<li>' + html.escape(platform) + ': <a href="' + quote(relative, safe='/') + '">' + html.escape(source.name) + '</a> · <a href="' + quote(relative, safe='/') + '.sha256">SHA-256</a></li>')
        page = '''<!doctype html>
<html lang="en-GB"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>WebTech_ASE downloads</title><link rel="stylesheet" href="assets/site.css"><style>main{max-width:76rem;margin:auto;padding:1rem}table{border-collapse:collapse;width:100%}th,td{text-align:left;padding:.65rem;border:1px solid #c4ccd4}th{font-weight:700}.scroll{overflow:auto}a:focus-visible{outline:3px solid #0756aa;outline-offset:3px}</style></head>
<body><main><h1>WebTech_ASE downloads</h1><p>English-language teaching materials from Antonio Clim. The repository remains a work in progress. Each selected distribution carries its own qualification status.</p>
<h2>Weekly downloads</h2><div class="scroll"><table><caption>Planned student distributions</caption><thead><tr><th scope="col">Week</th><th scope="col">Language</th><th scope="col">Version</th><th scope="col">Status</th><th scope="col">Files and instructions</th></tr></thead><tbody>''' + '\n'.join(rows) + '''</tbody></table></div>
<h2>Opening Week 01 and Week 02</h2><ol><li>Extract the outer weekly ZIP into a new folder.</li><li>Verify the hashes of both inner student ZIPs against SHA256SUMS.txt.</li><li>Extract each inner ZIP separately, read its README and run VERIFY_PACKAGE.</li><li>Week 01 course: OPEN_PRESENTATION. Week 02 course: START_COURSE_02. Both seminars: OPEN_BEGINNER_GUIDE. Use the .cmd launcher on Windows or the .sh launcher on macOS/Linux.</li></ol><p>Checksums prove byte identity. They do not establish browser, native-platform, Word, Moodle or teaching-pilot acceptance.</p>
<h2>Environment setup</h2><ul>''' + '\n'.join(setup_rows) + '''</ul><p><a href="''' + github + '''00_START_HERE/STUDENT_QUICK_START.md">Student quick start</a> · <a href="''' + github + '''SUPPORT.md">Support</a> · <a href="https://github.com/antonioclim/WebTech_ASE">Repository</a></p></main></body></html>
'''
        (out / 'index.html').write_text(page, encoding='utf-8')
        (out / '404.html').write_text('<!doctype html><html lang="en-GB"><head><meta charset="utf-8"><title>Page not found</title></head><body><main><h1>Page not found</h1><p><a href="' + github + '90_RELEASES/README.md">Open the download catalogue on GitHub</a></p></main></body></html>\n', encoding='utf-8')
        (out / 'downloads.json').write_text(json.dumps(sorted(records, key=lambda row: row['path']), indent=2) + '\n', encoding='utf-8')
        (out / '.nojekyll').write_text('', encoding='utf-8')
        print(f'BUILT_PAGES_PAYLOAD: {out} ({len(records)} ZIP assets; no deployment performed)')
        return 0
    except (ValueError, KeyError, OSError) as exc:
        parser.exit(2, f'FAIL_PAGES_BUILD: {exc}\n')


if __name__ == '__main__':
    raise SystemExit(main())
