(function(){'use strict';const s=JSON.parse(document.getElementById('s13-schema').textContent),C=S13FormCore,form=document.getElementById('fields'),status=document.getElementById('status'),printRoot=document.getElementById('printout');let values=C.defaults(s),provenance='LOCAL_REPORTED_DRAFT',revision=0,epoch=0,saveTimer=null,prepared=null;const confirmations=new Set(['privacy_check','declaration','pdf_review_submission']);
 const say=(message,error=false)=>{status.textContent=message;status.setAttribute('role',error?'alert':'status');};
 function controls(){return C.list(s).map(f=>document.getElementById(f.id));}
 function renderValues(){for(const f of C.list(s))document.getElementById(f.id).value=values[f.id];}
 function read(){return Object.fromEntries(C.list(s).map(f=>[f.id,document.getElementById(f.id).value]));}
 function cancelPending(){epoch++;if(saveTimer!==null)clearTimeout(saveTimer);saveTimer=null;document.getElementById('import-file').value='';}
 function invalidate(id){cancelPending();revision++;prepared=null;printRoot.replaceChildren();if(!confirmations.has(id)){values=C.clearConfirmations(values);for(const fid of confirmations)document.getElementById(fid).value=values[fid];}document.getElementById('snapshot-state').textContent='Print snapshot invalidated. The next print uses the current fields.';}
 function save(){saveTimer=null;try{localStorage.setItem(s.localStorageKey,JSON.stringify(C.pack(values,s,provenance)));say('Draft stored locally. Keep an external JSON backup too.');}catch{say('Local storage is unavailable. Your memory draft remains open. Export JSON before closing this tab.',true);}}
 function scheduleSave(){if(document.getElementById('autosave').checked){if(saveTimer!==null)clearTimeout(saveTimer);const token=epoch;saveTimer=setTimeout(()=>{if(token===epoch)save();},450);}}
 for(const sec of s.sections){const fieldset=document.createElement('fieldset');const legend=document.createElement('legend');legend.textContent=sec.title;fieldset.append(legend);for(const f of sec.fields){const wrap=document.createElement('div');wrap.className='field';const label=document.createElement('label');label.htmlFor=f.id;label.textContent=f.label+' ('+f.phase+')';const input=document.createElement(f.kind==='textarea'?'textarea':f.kind==='select'?'select':'input');input.id=f.id;input.name=f.id;input.maxLength=f.max;input.setAttribute('aria-describedby',f.id+'-help');if(f.kind==='text')input.type='text';if(f.kind==='textarea')input.rows=f.id==='p01_actual_or_model'?10:4;if(f.options)for(const option of f.options){const o=document.createElement('option');o.value=option;o.textContent=option||'Choose a state';input.append(o);}if(['seminar_id','kit_version'].includes(f.id))input.readOnly=true;const help=document.createElement('p');help.id=f.id+'-help';help.className='help';help.textContent=f.help;wrap.append(label,help,input);fieldset.append(wrap);}form.append(fieldset);}
 renderValues();form.addEventListener('input',e=>{if(!e.target.name)return;values=read();invalidate(e.target.name);scheduleSave();say('Edited. Previous privacy, truthfulness and PDF review confirmations were cleared after a material edit.');});
 function validate(mode){values=read();const result=C.check(values,s,mode);for(const control of controls())control.removeAttribute('aria-invalid');if(result.errors.length){for(const e of result.errors)document.getElementById(e.id).setAttribute('aria-invalid','true');document.getElementById(result.errors[0].id).focus();say(result.state+': '+result.errors.map(e=>e.message).join(' '),true);}else say(result.state+'. This does not certify actual execution, native browser or Word acceptance, Gemini authenticity or Moodle submission.');return result;}
 document.getElementById('check-core').addEventListener('click',()=>validate('core'));document.getElementById('check-final').addEventListener('click',()=>validate('final'));
 document.getElementById('autosave').addEventListener('change',()=>{if(document.getElementById('autosave').checked)save();else{if(saveTimer!==null)clearTimeout(saveTimer);saveTimer=null;say('Autosave disabled. Your draft remains in memory.');}});
 document.getElementById('restore').addEventListener('click',()=>{cancelPending();try{const text=localStorage.getItem(s.localStorageKey);if(text===null){say('No S13 saved draft was found.');return;}const draft=C.cleanImport(text,s);values=draft.values;provenance=draft.provenance;revision++;prepared=null;printRoot.replaceChildren();renderValues();say('Restored as an unverified draft. Confirmations were reset.');}catch(e){say('Restore refused or storage blocked: '+e.message+'. Current memory draft remains open.',true);}});
 document.getElementById('export').addEventListener('click',()=>{try{values=read();const text=JSON.stringify(C.pack(values,s,provenance),null,2)+'\n';const blob=new Blob([text],{type:'application/json;charset=utf-8'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=(C.filename(values)||'TW2026_S13_DRAFT.pdf').replace(/\.pdf$/,'.json');document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),0);say('JSON backup requested. Verify the file is present before closing.');}catch(e){say('Export refused: '+e.message,true);}});
 document.getElementById('import-file').addEventListener('change',async e=>{const file=e.target.files&&e.target.files[0];if(!file)return;cancelPending();const token=epoch,admittedBytes=file.size;if(!Number.isSafeInteger(admittedBytes)||admittedBytes<0||admittedBytes>s.maxImportBytes){say('Import refused before file reading: maximum 2 MB.',true);return;}try{const bytes=await file.arrayBuffer();if(token!==epoch)return;if(bytes.byteLength!==admittedBytes||bytes.byteLength>s.maxImportBytes)throw Error('Import byte length does not match the admitted file size.');const text=new TextDecoder('utf-8',{fatal:true}).decode(bytes);const draft=C.cleanImport(text,s);if(!confirm('Replace this memory draft with the imported unverified draft? Export first if needed.'))return;if(token!==epoch)return;values=draft.values;provenance=draft.provenance;revision++;prepared=null;printRoot.replaceChildren();renderValues();say('Imported unverified draft. Review evidence and reconfirm privacy, truthfulness and the actual PDF.');scheduleSave();}catch(err){if(token===epoch)say('Import refused: '+err.message+'. Current memory draft remains open.',true);}});
 document.getElementById('reset').addEventListener('click',()=>{if(!confirm('Export JSON first if you need this draft. Reset only this S13 draft and cancel pending import and autosave?'))return;cancelPending();document.getElementById('autosave').checked=false;values=C.defaults(s);provenance='LOCAL_REPORTED_DRAFT';revision++;prepared=null;printRoot.replaceChildren();renderValues();try{localStorage.removeItem(s.localStorageKey);say('S13 draft reset. Other local keys were not touched.');}catch{say('Memory draft reset. Storage removal was denied; export a new backup before closing.',true);}document.getElementById('student_code').focus();});
 function materialise(){values=read();const q=C.check(values,s,'final');const fragment=document.createDocumentFragment(),title=document.createElement('h1');title.textContent='S13 individual evidence';fragment.append(title);const banner=document.createElement('p');banner.className='print-banner';banner.textContent=q.ok?'REVIEWED STRUCTURE WITH USER-REPORTED EVIDENCE - execution and submission remain subject to review.':'DRAFT - REQUIRED EVIDENCE OR REVIEW IS UNRESOLVED. Keep reasons and next actions visible.';fragment.append(banner);const meta=document.createElement('p');meta.textContent='Kit 1.2.0 | '+provenance+' | Suggested filename: '+(C.filename(values)||'enter approved code')+' | Actual Gemini response: '+(C.response(values)===null?'null': 'user-reported excerpt below')+'.';fragment.append(meta);for(const sec of s.sections){const heading=document.createElement('h2');heading.textContent=sec.title;fragment.append(heading);for(const f of sec.fields){const block=document.createElement('section');block.className='print-field';const label=document.createElement('h3');label.textContent=f.label+' ['+f.id+']';const body=document.createElement('p');body.textContent=values[f.id]||'(blank)';block.append(label,body);fragment.append(block);}}printRoot.replaceChildren(fragment);prepared={revision,classification:q.state};document.getElementById('snapshot-state').textContent='Current text snapshot prepared at revision '+revision+'. Print is not a submission.';return q;}
 document.getElementById('prepare').addEventListener('click',()=>{materialise();say('Current fields materialised for print. Check the full preview and save one readable A4 PDF. Draft evidence retains the banner.');});document.getElementById('print').addEventListener('click',()=>{materialise();window.print();});window.addEventListener('beforeprint',materialise);
 document.getElementById('copy-name').addEventListener('click',async()=>{values=read();const name=C.filename(values);const fallback=document.getElementById('filename-fallback');fallback.value=name||'';if(!name){say('Enter your approved student code first.',true);return;}try{if(!navigator.clipboard)throw Error('Clipboard unavailable');await navigator.clipboard.writeText(name);say('Suggested filename copied. Confirm the institution approves your code.');}catch{fallback.focus();fallback.select();say('Clipboard unavailable. The filename is selected; press Ctrl+C or use the platform copy command.',true);}});
 say('Memory draft opened. Actual environment fields remain blank. Autosave is off. Export JSON before closing.');
})();
