/** Root-launcher entry point. No install, download, network fallback or PID guessing. */
import {spawn} from 'node:child_process';import {join,resolve} from 'node:path';import {fileURLToPath} from 'node:url';
import {ROOT,config,boundary,verifyPackage} from './integrity.mjs';import {environment} from './environment.mjs';import {runBounded,classify,cleanEnvironment} from './runner.mjs';
const projects=['p02','p01','p03'];const supplementalNames=['supplemental updated ascending options and fresh structures match the contract','supplemental actual API updated ascending and repeated closed parameters are correct'];
export async function readiness(id){const source=await boundary(id);if(!source.ok)return {source,environment:{ready:false,status:'NOT_MEASURED_AFTER_SOURCE_BLOCK'},ready:false};const info=await environment(id,{loadNative:true});return {source,environment:info,ready:info.ready};}
export async function executeTests(id='p02',mode='complete'){
 if(!projects.includes(id)||!['initial','complete','baseline','objective','regression'].includes(mode))throw Error('Use P02 by default; test mode baseline, objective, regression or complete');const c=await config(id),edge=await boundary(id);
 if(mode==='initial'&&(id!=='p02'||!edge.untouched))return {ok:false,status:'BLOCKED',reason:'INITIAL requires untouched required P02 target; use TEST/VERIFY_WORK_RESULT after editing',boundary:edge,runs:[]};
 const gate=await readiness(id);const report={project:id,mode,evidenceClass:'GUARDED_CANONICAL_ORM_SQLITE_ATTEMPT',gate,runs:[],referenceAcceptance:false};if(!gate.ready)return {...report,ok:false,status:'BLOCKED',reason:'Measured runtime, protected sources or dependency/native prerequisites are not ready; no application suite started'};
 const categories=['initial','complete'].includes(mode)?['baseline','objective','regression',...(mode==='complete'?['full',...(id==='p02'?['supplemental']:[])]:[])]:[mode];
 for(const category of categories){const kinds=category==='full'?['baseline','objective','regression']:[category],names=category==='supplemental'?supplementalNames:kinds.flatMap(k=>c.tests[k]),files=category==='supplemental'?[join(ROOT,'tools/supplemental.test.mjs')]:kinds.map(k=>join(ROOT,c.root,'tests/'+k+'.test.js'));const result=await runBounded(process.execPath,['--test','--test-reporter=tap','--test-concurrency=1',...files],{cwd:join(ROOT,c.root),timeout:30000});report.runs.push({category,expectedNames:names,evidenceScope:category==='supplemental'?'DERIVED_SUPPLEMENTAL_NOT_CANONICAL':'CANONICAL_TEST_BYTES',...result,verdict:classify(result,names,{initialAssertions:mode==='initial'&&category==='objective'})});}
 report.after=await boundary(id);report.ok=report.runs.every(r=>r.verdict.ok)&&report.after.ok&&report.after.targetSha256===edge.targetSha256;report.status=report.ok?'PASS_DECLARED_EXECUTED_SCOPE':'FAIL_CLOSED';report.canonicalCasesAvailable=Object.values(c.tests).reduce((sum,names)=>sum+names.length,0);const parsedOutcomes=report.runs.filter(r=>['PASS_NAMED_SUITE','EXPECTED_INITIAL_ASSERTIONS','ASSERTION_OR_TEST_FAIL'].includes(r.verdict.status));report.uniqueCanonicalCasesWithParsedOutcome=new Set(parsedOutcomes.filter(r=>r.category!=='supplemental').flatMap(r=>r.expectedNames)).size;report.uniqueSupplementalCasesWithParsedOutcome=new Set(parsedOutcomes.filter(r=>r.category==='supplemental').flatMap(r=>r.expectedNames)).size;report.limitation='Focused and aggregate categories repeat canonical cases. A pass is measured execution in this environment, not Windows/macOS/browser/Moodle acceptance or evidence authenticity.';return report;
}
export async function boundedObservation(action,id){const gate=await readiness(id);if(!gate.ready)return {ok:false,status:'BLOCKED',gate,reason:'Strict runtime, protected source or native prerequisites unavailable; no database opened'};const result=await runBounded(process.execPath,[join(ROOT,'tools/worker.mjs'),action],{cwd:ROOT,timeout:30000,maxBytes:2_000_000});let observation=null,parseError=null;try{observation=JSON.parse(result.stdout);}catch(e){parseError=e.message;}const fault=result.spawnError||result.timedOut||result.overflow||result.signal;return {ok:!fault&&result.exit===0&&observation?.ok===true,status:fault?'EXECUTION_FAULT_CLEANUP_UNKNOWN':result.exit===0&&observation?.ok===true?'PASS_ACTUAL_OBSERVATION':'FAIL_OR_INCOMPLETE_OBSERVATION',gate,result,observation,parseError,cleanup:fault?'UNKNOWN_AFTER_FORCED_OR_SIGNAL_TERMINATION':observation?.cleanup??'NOT_CONFIRMED',limitation:'Direct child bounded, not descendant containment. Observation class and actual cleanup must be read separately.'};}
export async function start(){const gate=await readiness('p02');if(!gate.ready){console.log(JSON.stringify({ok:false,status:'BLOCKED',gate,reason:'No listener or application database started'},null,2));return 2;}
 return new Promise(resolveExit=>{let ready=false,closed=false,stopRequested=false,fault=null,outputBytes=0,startTimer,stopTimer,grace,settled=false,exitCode=null,exitSignal=null;const child=spawn(process.execPath,[join(ROOT,'tools/worker.mjs'),'serve'],{cwd:ROOT,env:cleanEnvironment(),shell:false,stdio:['ignore','pipe','pipe','ipc']});
 const finish=(controllerFallback=false)=>{if(settled)return;settled=true;clearTimeout(startTimer);clearTimeout(stopTimer);clearTimeout(grace);process.removeListener('SIGINT',requestStop);process.removeListener('SIGTERM',requestStop);const ok=closed&&exitCode===0&&!fault&&!controllerFallback;if(!ok)console.error(JSON.stringify({status:fault??'UNEXPECTED_SERVER_EXIT',code:exitCode,signal:exitSignal,ready,controllerFallback,cleanup:closed&&!controllerFallback?'CONFIRMED_CLOSED':'UNKNOWN',scope:'OWNED_DIRECT_CHILD_ONLY_DESCENDANTS_NOT_CONTAINED'}));resolveExit(ok?0:1);};
 const force=(reason)=>{fault??=reason;child.kill('SIGKILL');if(!grace)grace=setTimeout(()=>{child.stdout?.destroy();child.stderr?.destroy();if(child.connected)try{child.disconnect();}catch(_){}child.unref();finish(true);},1000);};const requestStop=()=>{if(stopRequested)return;stopRequested=true;console.log('STOP_REQUESTED: waiting for this owned child listener and database to close');if(child.connected)child.send({type:'stop'});stopTimer=setTimeout(()=>force('SHUTDOWN_TIMEOUT_CLEANUP_UNKNOWN'),5000);};
 startTimer=setTimeout(()=>force('STARTUP_TIMEOUT_CLEANUP_UNKNOWN'),15000);process.once('SIGINT',requestStop);process.once('SIGTERM',requestStop);
 for(const kind of ['stdout','stderr'])child[kind].on('data',d=>{outputBytes+=d.length;if(outputBytes>2_000_000){force('OUTPUT_BOUND_CLEANUP_UNKNOWN');return;}process[kind].write(d);});
 child.on('message',m=>{if(m?.type==='ready'&&!ready){if(typeof m.origin!=='string'||!/^http:\/\/127\.0\.0\.1:[1-9][0-9]{0,4}$/.test(m.origin)||Number(m.origin.split(':').pop())>65535)return force('INVALID_READY');ready=true;clearTimeout(startTimer);console.log('READY '+m.origin);console.log('P02 memory fixture only. Keep this terminal open; Ctrl+C once here stops your owned application.');}else if(m?.type==='closed'&&m.listenerClosed===true&&m.databaseClosed===true){closed=true;console.log('STOPPED: listener and database closed');}else if(m?.type==='close-failed'){fault='CLOSE_FAILED_CLEANUP_UNKNOWN';console.error(fault+': '+m.message);}else force('UNEXPECTED_CHILD_CONTROL_MESSAGE');});
 child.on('error',e=>{fault='SPAWN_ERROR: '+(e.code||e.message);});child.on('exit',(code,signal)=>{exitCode=code;exitSignal=signal;});child.on('close',(code,signal)=>{exitCode=code;exitSignal=signal;finish();});
 });
}
export async function main(args=process.argv.slice(2)){const [action,...tail]=args;
 if(action==='package'){if(tail.length)throw Error('VERIFY_PACKAGE takes no arguments');const r=await verifyPackage();console.log(JSON.stringify(r,null,2));return r.ok?0:2;}
 if(action==='environment'){if(tail.length>1||!['p02','p01','p03','lifecycle'].includes(tail[0]??'p02'))throw Error('CHECK_ENVIRONMENT [p02|p01|p03|lifecycle]');const r=await readiness(tail[0]??'p02');console.log(JSON.stringify(r,null,2));return r.ready?0:2;}
 if(action==='initial'||action==='work'||action==='test'){if(tail.length>(action==='test'?2:1)||!projects.includes(tail[0]??'p02'))throw Error('Invalid project/extra arguments');const r=await executeTests(tail[0]??'p02',action==='initial'?'initial':action==='work'?'complete':tail[1]??'complete');console.log(JSON.stringify(r,null,2));return r.ok?0:r.status==='BLOCKED'?2:1;}
 if(action==='start'){if(tail.length>1||(tail[0]&&tail[0]!=='p02'))throw Error('START supports only required P02');return start();}
 if(action==='observe-query'||action==='lifecycle'){if(tail.length)throw Error('Observation launchers take no arguments or personal database path');const r=await boundedObservation(action,action==='lifecycle'?'lifecycle':'p02');console.log(JSON.stringify(r,null,2));return r.ok?0:r.status==='BLOCKED'?2:1;}
 if(action==='stop'){if(tail.length)throw Error('STOP takes no PID or other argument');console.log('NO_PROCESS_SIGNAL_SENT. Return to the terminal that printed READY for your P02 application. Press Ctrl+C once in that terminal. Wait for STOPPED: listener and database closed. If a timeout, forced termination or close error appears, record cleanup UNKNOWN. Do not kill a guessed PID or an unrelated Node process.');return 0;}
 throw Error('Use root launchers: VERIFY_PACKAGE, CHECK_ENVIRONMENT, VERIFY_INITIAL_STATE, VERIFY_WORK_RESULT, TEST, START, STOP, OBSERVE_QUERY or OBSERVE_FILE_LIFECYCLE');
}
if(process.argv[1]&&resolve(process.argv[1])===fileURLToPath(import.meta.url))main().then(c=>process.exitCode=c).catch(e=>{console.error('BLOCKED_OR_FAILED: '+e.message);process.exitCode=2;});
