/** Read-only prerequisite report; never installs, downloads or substitutes a dependency. */
import {readFile,realpath,access} from 'node:fs/promises';import {join,dirname,resolve,sep,delimiter} from 'node:path';import {createRequire} from 'node:module';import {config,ROOT} from './integrity.mjs';import {runBounded} from './runner.mjs';
export const REQUIRED_NODE='v24.21.0',REQUIRED_NPM='11.19.0';
export async function findNpmCli(){const dirs=[dirname(process.execPath),...(process.env.PATH||'').split(delimiter).filter(Boolean)];const candidates=[];for(const dir of dirs){candidates.push(join(dir,'node_modules/npm/bin/npm-cli.js'),resolve(dir,'../lib/node_modules/npm/bin/npm-cli.js'));for(const name of ['npm','npm.cmd'])try{const p=await realpath(join(dir,name));if(p.endsWith('npm-cli.js'))candidates.push(p);else candidates.push(join(dirname(p),'node_modules/npm/bin/npm-cli.js'));}catch(_){} }
 for(const p of [...new Set(candidates)])try{await access(p);return p;}catch(_){}return null;
}
export async function environment(id='p02',{root=ROOT,loadNative=false}={}){const c=await config(id,root),directory=join(root,c.root),pkg=JSON.parse(await readFile(join(directory,'package.json'),'utf8')),lock=JSON.parse(await readFile(join(directory,'package-lock.json'),'utf8')),req=createRequire(join(directory,'package.json'));const npmCli=await findNpmCli();const npmResult=npmCli?await runBounded(process.execPath,[npmCli,'--version'],{timeout:5000,maxBytes:65536}):null;const npm=npmResult?.exit===0&&!npmResult.spawnError&&!npmResult.signal&&!npmResult.timedOut&&!npmResult.overflow&&!npmResult.controllerFallback&&/^\d+\.\d+\.\d+\n?$/.test(npmResult.stdout)?npmResult.stdout.trim():null;const dependencies=[];
 for(const name of Object.keys(pkg.dependencies||{})){let actual=null,resolved=null,error=null;const expected=lock.packages?.['node_modules/'+name]?.version;try{resolved=req.resolve(name+'/package.json');if(!(await realpath(resolved)).startsWith(resolve(directory,'node_modules')+sep))throw Error('NOT_PROJECT_LOCAL');actual=JSON.parse(await readFile(resolved,'utf8')).version;if(!expected||actual!==expected)throw Error('LOCK_VERSION_MISMATCH');}catch(e){error=e.code||e.message;}dependencies.push({name,expected,actual,resolved,error});}
 const versionsMatch=process.version===REQUIRED_NODE&&npm===REQUIRED_NPM,resolutionReady=dependencies.every(d=>!d.error);let native={attempted:false,status:'NOT_LOADED',reason:loadNative?'Strict runtime/dependency guard must pass first':'Resolution only; native loading requires a separately guarded execution'};
 if(loadNative&&versionsMatch&&resolutionReady){const result=await runBounded(process.execPath,[join(ROOT,'tools/worker.mjs'),'native-load',id],{cwd:root,timeout:10000,maxBytes:65536});let parsed=null;try{parsed=JSON.parse(result.stdout);}catch(_){}native={attempted:true,status:result.exit===0&&!result.spawnError&&!result.signal&&!result.timedOut&&!result.overflow&&!result.controllerFallback&&!result.stderr.trim()&&parsed?.status==='NATIVE_SQLITE3_MODULE_LOADED'&&parsed.databaseOpened===false?'LOADED':'BLOCKED_OR_FAILED',result};}
 return {project:id,node:process.version,npm,requiredNode:REQUIRED_NODE,requiredNpm:REQUIRED_NPM,versionsMatch,npmMeasurement:{command:npmResult?.command??null,args:npmResult?.args??null,stderr:npmResult?.stderr??'',fault:npmResult?.spawnError??(npmResult?.timedOut?'TIMEOUT':npmResult?.overflow?'OUTPUT_BOUND':npmResult?.signal?'SIGNAL':npmResult?.controllerFallback?'CONTROLLER_FALLBACK':null)},dependencies,resolutionReady,native,ready:versionsMatch&&resolutionReady&&(!loadNative||native.status==='LOADED'),qualification:native.status==='LOADED'?'NATIVE_MODULE_LOAD_ONLY_NOT_ORM_OR_SQL_QUALIFICATION':'SOURCE_RESOLUTION_ONLY_NOT_NATIVE_QUALIFICATION'};
}
export function requireReady(info){if(!info.ready)throw Error('ENVIRONMENT_BLOCKED: record measured versions and dependency/native errors; use the separately prepared teaching environment. No installation is performed.');return info;}
