import assert from "node:assert/strict";
import test from "node:test";
import { fixture, emit } from "./helpers.mjs";
import { createFrame } from "./fakes.mjs";

test("descriptor validation, exact origin/source/version, and one listener fail closed", () => { const f = fixture(); assert.equal(f.host.count(), 1); assert.throws(() => f.coordinator.register({ name: "catalog", origin: "https://x.example", window: {} })); f.host.emit({ origin: "https://evil.example", source: f.catalog, data: { type: "fragment.ready", version: 1, generation: 1, payload: {} } }); f.host.emit({ origin: "https://catalog.example", source: {}, data: { type: "fragment.ready", version: 1, generation: 1, payload: {} } }); f.host.emit({ origin: "https://catalog.example", source: f.catalog, data: { type: "fragment.ready", version: 2, generation: 1, payload: {} } }); assert.equal(f.coordinator.diagnostics.readyCount, 0); f.coordinator.dispose(); });
test("readiness queues only latest state and sends exact target origin", () => { const f = fixture(); assert.equal(f.coordinator.send("details", "details.show", { item: { id: "old" } }), false); f.coordinator.send("details", "details.show", { item: { id: "new" } }); emit(f, "details", "fragment.ready"); assert.deepEqual(f.details.sent(), [{ message: { type: "details.show", version: 1, generation: 1, payload: { item: { id: "new" } } }, origin: "https://details.example" }]); assert.deepEqual(f.ready, [["details", 1]]); f.coordinator.dispose(); });
test("catalog intent loads authoritative state then targets details", async () => { const f = fixture(); emit(f, "details", "fragment.ready"); emit(f, "catalog", "item.selected", { itemId: "item-2", role: "admin" }); await new Promise((resolve) => setImmediate(resolve)); assert.deepEqual(f.selections, ["item-2"]); assert.equal(f.details.sent().at(-1).message.payload.item.id, "item-2"); emit(f, "catalog", "item.selected", { itemId: "bad id" }); assert.equal(f.selections.length, 1); f.coordinator.dispose(); });
test("replacement generation rejects stale messages and requires new readiness", () => { const f = fixture(); emit(f, "catalog", "fragment.ready"); const replacement = createFrame(); f.coordinator.replace("catalog", replacement, 2); emit(f, "catalog", "item.selected", { itemId: "item-1" }); assert.equal(f.selections.length, 0); f.host.emit({ origin: "https://catalog.example", source: replacement, data: { type: "fragment.ready", version: 1, generation: 1, payload: {} } }); assert.equal(f.coordinator.diagnostics.readyCount, 0); f.host.emit({ origin: "https://catalog.example", source: replacement, data: { type: "fragment.ready", version: 1, generation: 2, payload: {} } }); assert.equal(f.coordinator.diagnostics.readyCount, 1); f.coordinator.dispose(); });
test("timeout and disposal expose unavailable state and clean all instances", async () => { const f = fixture({ readinessTimeoutMs: 5 }); await new Promise((resolve) => setTimeout(resolve, 10)); assert.deepEqual(f.unavailable.sort(), ["catalog", "details"]); f.coordinator.dispose(); assert.equal(f.host.count(), 0); assert.deepEqual(f.coordinator.diagnostics, { fragmentCount: 0, readyCount: 0 }); f.coordinator.dispose(); assert.throws(() => f.coordinator.register({ name: "x", origin: "https://x.example", window: {} }), /disposed/i); });
