import {assessEnvironment,REFERENCE} from './environment.mjs';
import {readFileSync,readdirSync,lstatSync} from 'node:fs';import{createHash}from'node:crypto';import{dirname,join,resolve}from'node:path';import{fileURLToPath}from'node:url';
const ROOT=dirname(fileURLToPath(import.meta.url));const CONTROL='CLASSROOM_BOUNDARY.json';
const environment=await assessEnvironment({unit:'S14',operation:'source-boundary',cwd:dirname(ROOT),command:'node CLASSROOM_RC6/verify.mjs '+(process.argv[1]&&resolve(process.argv[1])===fileURLToPath(import.meta.url)?(process.argv[2]||'work'):'work'),features:['node-core'],usesNpm:false});
function digest(path){const s=lstatSync(path);if(!s.isFile()||s.isSymbolicLink())throw Error('NON_REGULAR_SOURCE '+path);return createHash('sha256').update(readFileSync(path)).digest('hex');}
function safe(path){if(typeof path!=='string'||!path||path.includes('\\')||path.startsWith('/')||path.split('/').some(p=>!p||p==='.'||p==='..'||/[<>:"|?*\x00-\x1f]/.test(p)||/[. ]$/.test(p)||/^(con|prn|aux|nul|com[1-9]|lpt[1-9])(?:\.|$)/i.test(p)))throw Error('INVALID_BOUNDARY_PATH');return path;}
function exactKeys(object,keys){if(!object||Object.getPrototypeOf(object)!==Object.prototype||Object.keys(object).sort().join('\0')!==[...keys].sort().join('\0'))throw Error('INVALID_BOUNDARY_SCHEMA');}
function config(){const c=JSON.parse(readFileSync(join(ROOT,CONTROL),'utf8'));exactKeys(c,['schema','referenceNode','mutable','protected','excludedRuntimeDirectories','sourceManifestExcluded','trust']);if(c.schema!=='webtech-classroom-boundary/v1'||c.referenceNode!=='v24.21.0')throw Error('INVALID_BOUNDARY_VERSION');for(const field of ['mutable','protected']){if(!c[field]||Object.getPrototypeOf(c[field])!==Object.prototype)throw Error('INVALID_BOUNDARY_RECORD');for(const[p,h]of Object.entries(c[field]))if(!safe(p)||typeof h!=='string'||!/^[0-9a-f]{64}$/.test(h))throw Error('INVALID_BOUNDARY_HASH');}if(Object.keys(c.mutable).some(p=>Object.hasOwn(c.protected,p)))throw Error('OVERLAPPING_BOUNDARY');if(!Array.isArray(c.excludedRuntimeDirectories)||c.excludedRuntimeDirectories.some(p=>!['REACT/node_modules','REACT/dist'].includes(p))||new Set(c.excludedRuntimeDirectories).size!==c.excludedRuntimeDirectories.length)throw Error('UNDECLARED_RUNTIME_EXCLUSION');if(!Array.isArray(c.sourceManifestExcluded)||c.sourceManifestExcluded.some(p=>!['SOURCE_MANIFEST.json',CONTROL].includes(p))||!c.sourceManifestExcluded.includes(CONTROL)||new Set(c.sourceManifestExcluded).size!==c.sourceManifestExcluded.length)throw Error('INVALID_SELF_CONTROL_EXCLUSION');return c;}
function inventory(c){const paths=[];function walk(dir,prefix=''){for(const e of readdirSync(dir,{withFileTypes:true})){const p=safe(prefix+e.name),full=join(dir,e.name),stat=lstatSync(full);if(stat.isSymbolicLink())throw Error('SOURCE_SYMLINK '+p);if(c.excludedRuntimeDirectories.includes(p)){if(!stat.isDirectory())throw Error('RUNTIME_ROOT_NOT_DIRECTORY '+p);continue;}if(stat.isDirectory())walk(full,p+'/');else if(stat.isFile())paths.push(p);else throw Error('NON_REGULAR_SOURCE '+p);}}walk(ROOT);const expected=[...Object.keys(c.protected),...Object.keys(c.mutable),...c.sourceManifestExcluded].sort();if(JSON.stringify(paths.sort())!==JSON.stringify(expected))throw Error('SOURCE_SET_MISMATCH');return paths;}
export function boundarySnapshot(mode='work'){if(!['initial','work'].includes(mode))throw Error('INVALID_BOUNDARY_MODE');if(environment.exitCode)throw Error(JSON.stringify(environment));const c=config(),paths=inventory(c),hashes=Object.fromEntries(paths.map(p=>[p,digest(join(ROOT,p))]));for(const[p,h]of Object.entries(c.protected))if(hashes[p]!==h)throw Error('PROTECTED_SOURCE_CHANGED '+p);if(mode==='initial')for(const[p,h]of Object.entries(c.mutable))if(hashes[p]!==h)throw Error('INITIAL_TARGET_CHANGED '+p);return {schema:'webtech-classroom-boundary-snapshot/v1',root:ROOT,mode,hashes,runtimeExclusions:c.excludedRuntimeDirectories,sourceManifestExcluded:c.sourceManifestExcluded};}
export function assertBoundaryUnchanged(before){if(!before||before.root!==ROOT)throw Error('INVALID_BOUNDARY_SNAPSHOT');const c=config(),paths=inventory(c);if(JSON.stringify(paths.sort())!==JSON.stringify(Object.keys(before.hashes).sort()))throw Error('SOURCE_SET_CHANGED_DURING_CHECK');for(const[p,h]of Object.entries(before.hashes))if(digest(join(ROOT,p))!==h)throw Error('SOURCE_CHANGED_DURING_CHECK '+p);return true;}
if(process.argv[1]&&resolve(process.argv[1])===fileURLToPath(import.meta.url)){try{const [mode='work',...extra]=process.argv.slice(2);if(extra.length)throw Error('EXTRA_ARGUMENTS');const result=boundarySnapshot(mode);console.log(JSON.stringify({status:mode==='initial'?'PASS_INITIAL_CLASSROOM_SOURCE':'PASS_MUTABLE_CLASSROOM_BOUNDARY',sourceFiles:Object.keys(result.hashes).length,mutableSourceMode:mode,referenceNode:REFERENCE.node,observedNode:process.version,environmentStatus:environment.status,environment,runtimeDirectoriesUnverified:result.runtimeExclusions,truthAuthenticated:false,trust:'Unsigned local self-consistency boundary. Release/package identity is the external trust anchor. Work admits only listed learner targets; this does not satisfy original canonical completion or native qualification.'},null,2));}catch(e){console.error(JSON.stringify({status:'STOP_CLASSROOM_BOUNDARY',reason:e.message}));process.exitCode=2;}}
