
// Derived checks call the student's module. They do not implement the Dashboard.
import test from 'node:test';import assert from 'node:assert/strict';import {resolve}from'node:path';import{pathToFileURL}from'node:url';
const root=process.env.S04_PROJECT_ROOT;if(!root)throw Error('Use tools/gate.mjs so the project is identified explicitly.');
const{loadDashboard}=await import(pathToFileURL(resolve(root,'public/dashboard.js')));
const values={'/data/profile.json':{name:'Ada',team:'Web Lab'},'/data/tasks.json':[{status:'open'},{status:'done'},{status:'open'}],'/data/notices.json':['Review the diff','Run the checks']};
test('derived dashboard: exact supplied fixture and render return',async()=>{const states=[],paths=[];const result=await loadDashboard({fetchImpl:async p=>{paths.push(p);return{ok:true,status:200,json:async()=>structuredClone(values[p])};},render:m=>states.push(m)});assert.equal(result.state,'success');assert.deepEqual(paths,Object.keys(values));assert.deepEqual(states.map(s=>s.state),['loading','success']);assert.equal(states.at(-1),result);assert.equal(result.openTaskCount,2);assert.equal(result.totalTaskCount,3);assert.equal(result.notices.length,2);});
test('derived dashboard: independent initiation before deferred release',async()=>{const paths=[],pending=[];const result=loadDashboard({fetchImpl:p=>{paths.push(p);return new Promise(done=>pending.push(()=>done({ok:true,status:200,json:async()=>values[p]})));},render:()=>{}});await Promise.resolve();try{assert.equal(paths.length,3);}finally{pending.reverse().forEach(done=>done());}await result;});
test('derived dashboard: transport rejection is a returned error',async()=>{const states=[];const result=await loadDashboard({fetchImpl:async()=>{throw Error('controlled transport rejection');},render:m=>states.push(m)});assert.equal(result.state,'error');assert.equal(result.message,'controlled transport rejection');assert.deepEqual(states.map(x=>x.state),['loading','error']);});
test('derived dashboard: rejected status is not parsed',async()=>{let parsed=0;const result=await loadDashboard({fetchImpl:async()=>({ok:false,status:404,json:async()=>{parsed++;return{};}}),render:()=>{}});assert.equal(result.state,'error');assert.equal(parsed,0);assert.match(result.message,/request failed: \/data\/(profile|tasks|notices)\.json \(404\)/);});
