
// Assertion-first observations retain missing structure as an assertion, not a TypeError.
import test from'node:test';import assert from'node:assert/strict';import{resolve}from'node:path';import{pathToFileURL}from'node:url';import{Element,document,roots}from'./dom-model.mjs';
const root=process.env.S04_PROJECT_ROOT;if(!root)throw Error('Use tools/gate.mjs.');
const{renderTasks,bindTaskEvents}=await import(pathToFileURL(resolve(root,'public/task-view.js')));
test('derived task view: row structure and empty state',()=>{const{list}=roots();renderTasks([{id:'task-7',title:'A',completed:true}],{document,list});assert.equal(list.children.length,1,'Exactly one row is required before its fields are inspected.');const r=list.children[0];assert.equal(r.dataset.taskId,'task-7');assert.match(r.className,/completed/);assert.equal(r.children.length,3);assert.equal(r.children[0].checked,true);assert.equal(r.children[1].textContent,'A');assert.equal(r.children[2].dataset.action,'delete');renderTasks([],{document,list});assert.equal(list.children.length,1);assert.equal(list.children[0].className,'empty');});
test('derived task view: valid and blank submit with cleanup',()=>{const{form,list}=roots(),adds=[];const unbind=bindTaskEvents({form,list,onAdd:x=>adds.push(x),onToggle:()=>{},onDelete:()=>{}});assert.equal(typeof unbind,'function');form.elements.title.value='  Learn  ';const e=form.emit('submit');assert.deepEqual(adds,['Learn']);assert.equal(e.defaultPrevented,true);assert.equal(form.resets,1);form.elements.title.value='  ';const blank=form.emit('submit');assert.equal(blank.defaultPrevented,true);assert.equal(adds.length,1);assert.equal(form.resets,1);unbind();assert.equal(form.count()+list.count(),0);});
test('derived task view: nested action and unbind rebind deltas',()=>{const{form,list}=roots(),row=new Element('li'),toggle=new Element('input'),button=new Element('button'),span=new Element('span'),calls=[];row.dataset.taskId='task-7';toggle.dataset.action='toggle';button.dataset.action='delete';button.append(span);row.append(toggle,button);list.append(row);const opts={form,list,onAdd:()=>{},onToggle:id=>calls.push('t:'+id),onDelete:id=>calls.push('d:'+id)};let off=bindTaskEvents(opts);list.emit('click',{target:toggle});list.emit('click',{target:span});assert.deepEqual(calls,['t:task-7','d:task-7']);off();list.emit('click',{target:span});assert.equal(calls.length,2);off=bindTaskEvents(opts);list.emit('click',{target:span});assert.equal(calls.length,3);assert.equal(list.count(),1);off();assert.equal(list.count()+form.count(),0);});
test('derived task view: literal title and repeated render have no row listeners',()=>{const{list}=roots();const task=Object.freeze({id:'t',title:'<em>sample</em>',completed:false});for(let i=0;i<3;i++){renderTasks(Object.freeze([task]),{document,list});assert.equal(list.children.length,1);const r=list.children[0];assert.equal(r.children.length,3);assert.equal(r.children[1].textContent,task.title);assert.equal(r.count()+r.children.reduce((a,n)=>a+n.count(),0),0);}assert.equal(list.count(),0);});
