import assert from "node:assert/strict";
import { test } from "node:test";
import { authorize } from "../src/authorization-policy.js";
import { auth, fixture, withApp } from "./helpers.js";

test("read allows owner/moderator/admin and conceals unrelated or missing reports", async () => { for (const [session, id, status] of [["member-u1", "r1", 200], ["moderator-u2", "r1", 200], ["admin-u9", "r1", 200], ["member-u1", "r2", 404], ["admin-u9", "missing", 404]]) { const { app } = fixture(); await withApp(app, async (url) => assert.equal((await fetch(`${url}/api/reports/${id}`, { headers: auth(session) })).status, status)); } });
test("submit trusts repository ownership, conceals others, and leaves state precondition to route", async () => { const { app, repository } = fixture(); await withApp(app, async (url) => { const hostile = await fetch(`${url}/api/reports/r2/submit`, { method: "POST", headers: { ...auth("member-u1"), "content-type": "application/json" }, body: JSON.stringify({ ownerId: "u1", role: "admin", status: "draft" }) }); assert.equal(hostile.status, 404); assert.equal((await repository.findById("r2")).status, "draft"); assert.equal((await fetch(`${url}/api/reports/r4/submit`, { method: "POST", headers: auth("member-u1") })).status, 409); const allowed = await fetch(`${url}/api/reports/r1/submit`, { method: "POST", headers: auth("member-u1") }); assert.equal(allowed.status, 200); assert.equal((await allowed.json()).data.status, "submitted"); }); });
test("resolve allows moderator/admin, denies members, and enforces resource state", async () => { for (const [session, id, status] of [["member-u1", "r3", 403], ["moderator-u2", "r3", 200], ["admin-u9", "r1", 409]]) { const { app } = fixture(); await withApp(app, async (url) => assert.equal((await fetch(`${url}/api/reports/${id}/resolve`, { method: "POST", headers: auth(session) })).status, status)); } });
test("delete allows owner/admin and denies unrelated roles without body privilege", async () => { for (const [session, id, status] of [["member-u1", "r1", 204], ["moderator-u2", "r2", 204], ["admin-u9", "r2", 204], ["member-u1", "r2", 403], ["moderator-u2", "r1", 403]]) { const { app } = fixture(); await withApp(app, async (url) => assert.equal((await fetch(`${url}/api/reports/${id}`, { method: "DELETE", headers: { ...auth(session), "content-type": "application/json" }, body: JSON.stringify({ role: "admin", ownerId: session.endsWith("u1") ? "u1" : "u9" }) })).status, status)); } });
test("policy loads once, attaches frozen resource, fails unknown actions, and sanitizes loader errors", async () => { assert.throws(() => authorize({ action: "report:typo", loadResource: async () => null }), /Unsupported authorization action/); let loads = 0; let frozen = false; const repository = { async findById(id) { loads += 1; if (id === "boom") throw new Error("repository secret"); return Object.freeze({ id, ownerId: "u1", status: "draft" }); }, async submit() { return {}; }, async resolve() { return {}; }, async remove() {} }; const wrapped = (options) => { const middleware = authorize(options); return (request, response, next) => middleware(request, response, (error) => { if (!error) frozen = Object.isFrozen(request.authorizedResource); next(error); }); }; const { app } = fixture({ repository, authorize: wrapped }); await withApp(app, async (url) => { assert.equal((await fetch(`${url}/api/reports/r1`, { headers: auth("member-u1") })).status, 200); assert.equal(loads, 1); assert.equal(frozen, true); const failed = await fetch(`${url}/api/reports/boom`, { headers: auth("member-u1") }); assert.equal(failed.status, 500); assert.doesNotMatch(await failed.text(), /repository|secret|stack/i); }); });
