import assert from "node:assert/strict";
import test from "node:test";
import { fixture, headers, post, withApp } from "./helpers.js";

const job = (id, ownerId = "u1") => ({ id, data: { reportId: "report-1", ownerId, correlationId: id } });

test("enqueue stores minimal owner-bound data only after queue acceptance", async () => { const f = fixture(); await withApp(f.app, async (url) => { const response = await post(url, "report-1"); assert.equal(response.status, 202); assert.equal(response.headers.get("location"), "/api/exports/job-1"); assert.deepEqual(await response.json(), { data: { jobId: "job-1", status: "queued" } }); assert.deepEqual(f.added, [{ name: "export", data: { reportId: "report-1", ownerId: "u1", correlationId: "job-1" }, options: { jobId: "job-1", attempts: 3, backoff: { type: "exponential", delay: 1000 }, removeOnComplete: 100, removeOnFail: 100 } }]); }); });
test("enqueue failure is sanitized and creates no projection", async () => { const f = fixture({ queue: { async add() { throw new Error("redis password secret"); } } }); await withApp(f.app, async (url) => { const response = await post(url, "report-1"); assert.equal(response.status, 503); assert.deepEqual(await response.json(), { error: { code: "queue_unavailable", message: "Queue is temporarily unavailable" } }); assert.deepEqual(f.store.snapshot(), []); }); });
test("lifecycle publishes monotonic owner-scoped progress and safe completion", async () => { const f = fixture(); await f.lifecycle.enqueue({ principal: { id: "u1" }, reportId: "report-1" }); const current = job("job-1"); f.worker.emit("active", current); f.worker.emit("progress", current, 25); f.worker.emit("progress", current, 10); f.worker.emit("completed", current, { downloadId: "d1", format: "csv", path: "/secret" }); f.worker.emit("progress", current, 90); assert.deepEqual(f.lifecycle.findForOwner("job-1", "u1"), { jobId: "job-1", ownerId: "u1", reportId: "report-1", correlationId: "job-1", status: "completed", progress: 100, result: { downloadId: "d1", format: "csv" } }); assert.equal(f.eventSink.forOwner("u1").length, 3); assert.equal(f.eventSink.forOwner("u2").length, 0); assert.doesNotMatch(JSON.stringify(f.eventSink.all()), /secret|path/); });
test("failure is sanitized, terminal state is stable, and other owners are concealed", async () => { const f = fixture(); await f.lifecycle.enqueue({ principal: { id: "u1" }, reportId: "report-1" }); const current = job("job-1"); f.worker.emit("failed", current, new Error("redis stack secret")); f.worker.emit("completed", current, { downloadId: "late", format: "csv" }); assert.deepEqual(f.lifecycle.findForOwner("job-1", "u2"), null); assert.equal(f.lifecycle.findForOwner("job-1", "u1").status, "failed"); assert.doesNotMatch(JSON.stringify(f.eventSink.all()), /redis|stack|secret/); await withApp(f.app, async (url) => assert.equal((await fetch(`${url}/api/exports/job-1`, { headers: headers("malik-session") })).status, 404)); });
test("listener cleanup and independent lifecycle instances do not bleed", async () => { const one = fixture(); const two = fixture(); assert.equal(one.worker.listenerCount("completed"), 1); one.lifecycle.close(); assert.equal(one.worker.listenerCount("completed"), 0); await two.lifecycle.enqueue({ principal: { id: "u2" }, reportId: "r2" }); assert.equal(one.store.snapshot().length, 0); assert.equal(two.store.snapshot().length, 1); two.lifecycle.close(); });
