import {REFERENCE} from './environment.mjs';
import {assessActivityEnvironment} from './activity-environment.mjs';
import {readFileSync,lstatSync,readdirSync,mkdtempSync,rmSync,existsSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {createHash} from 'node:crypto';import {spawnSync} from 'node:child_process';import {fileURLToPath} from 'node:url';import {dirname,join} from 'node:path';
const root=dirname(fileURLToPath(import.meta.url)),config=JSON.parse(readFileSync(join(root,'contract.json'),'utf8'));
const exact=process.version===REFERENCE.node;
function sha(path){const stat=lstatSync(path);if(!stat.isFile()||stat.isSymbolicLink())throw Error('NON_REGULAR_SOURCE '+path);return createHash('sha256').update(readFileSync(path)).digest('hex');}
const [action='help',project='all',...tail]=process.argv.slice(2);if(action==='serve'){console.error(JSON.stringify({status:'STOP_UNSUPPORTED_CLASSROOM_COMMAND',seminar:'S06',command:'serve',reason:'This seminar uses Node module fixtures and ships no browser server. Use initial, check or observe.'}));process.exit(2);}if(tail.length||!['initial','check','observe'].includes(action)||!['all',...config.projects.map(p=>p.id)].includes(project)){console.error('Use node CLASSROOM_RC6/kit.mjs initial | check P01/P02/P03/all | observe P01/P02/P03/all');process.exit(2);}
const environment=await assessActivityEnvironment({unit:'S06/'+project,operation:action,cwd:dirname(root),command:'node CLASSROOM_RC6/kit.mjs '+action+' '+project,usesSqlite:true});console.error(JSON.stringify(environment));if(environment.exitCode)process.exit(environment.exitCode);
let temporaryWorkspace=null;
try{const manifest=JSON.parse(readFileSync(join(root,'SOURCE_MANIFEST.json'),'utf8'));const found=[];function walk(dir,prefix=''){for(const item of readdirSync(dir,{withFileTypes:true})){const p=prefix+item.name;if(item.isDirectory())walk(join(dir,item.name),p+'/');else{if(item.isSymbolicLink()||!item.isFile())throw Error('NON_REGULAR_SOURCE '+p);found.push(p);}}}walk(root);const expected=[...Object.keys(manifest.protected),...Object.keys(manifest.targets),'SOURCE_MANIFEST.json'].sort();if(JSON.stringify(found.sort())!==JSON.stringify(expected))throw Error('CLASSROOM_SOURCE_SET_CHANGED');for(const [p,digest]of Object.entries(manifest.protected))if(sha(join(root,p))!==digest)throw Error('PROTECTED_SOURCE_CHANGED '+p);for(const p of Object.keys(manifest.targets))sha(join(root,p));if(action==='initial')for(const[p,digest]of Object.entries(manifest.targets))if(sha(join(root,p))!==digest)throw Error('INITIAL_REQUIRES_ORIGINAL_STARTERS '+p);
 const before=Object.fromEntries(Object.keys(manifest.targets).map(p=>[p,sha(join(root,p))]));
 /* RC9_CLASSROOM_MODULE_ONLY */{const workerDirectory=mkdtempSync(join(tmpdir(),'webtech-S06-worker-'));let result,cleanupError;
 try{result=spawnSync(process.execPath,[join(root,'checks.mjs'),action,project],{cwd:root,env:{...process.env,TMPDIR:workerDirectory,TMP:workerDirectory,TEMP:workerDirectory},encoding:'utf8',timeout:10000,killSignal:'SIGKILL',maxBuffer:2000000});}
 finally{try{rmSync(workerDirectory,{recursive:true,force:true});}catch(error){cleanupError=error;}}
 temporaryWorkspace={directory:workerDirectory,parentOwned:true,cleanup:cleanupError?'FAILED':'REMOVED_AFTER_CHILD_STOP',directoryExists:existsSync(workerDirectory)};console.error(JSON.stringify({status:'OWNED_WORKER_TEMPORARY_DIRECTORY',...temporaryWorkspace}));if(cleanupError)throw Error('WORKER_TEMP_CLEANUP_FAILED '+cleanupError.code);if(result.stderr)process.stderr.write(result.stderr);if(result.error||result.signal||result.status===null)throw Error('BOUNDED_CHILD_FAULT '+(result.error?.code||result.signal||'NO_EXIT_STATUS'));let report;try{report=JSON.parse(result.stdout);}catch{throw Error('UNPARSEABLE_WORKER_OUTPUT '+String(result.stderr).slice(0,200));}const after=Object.fromEntries(Object.keys(manifest.targets).map(p=>[p,sha(join(root,p))]));if(JSON.stringify(before)!==JSON.stringify(after))throw Error('TARGET_CHANGED_DURING_CHECK');for(const [p,digest]of Object.entries(manifest.protected))if(sha(join(root,p))!==digest)throw Error('PROTECTED_SOURCE_CHANGED_DURING_CHECK '+p);console.log(JSON.stringify({...report,referenceNode:REFERENCE.node,referenceNodeMatch:exact,observedNode:process.version,environmentStatus:environment.status,temporaryWorkspace,sourceBoundary:'PROTECTED_FILES_AND_STABLE_TARGET_BYTES',nativeQualification:false,completionTimePilot:false,limitation:config.limitation},null,2));process.exitCode=result.status??1;}
}catch(error){console.error(JSON.stringify({status:'STOP_CLASSROOM_BOUNDARY_OR_EXECUTION',reason:error.message,referenceNode:REFERENCE.node,referenceNodeMatch:exact,observedNode:process.version,environmentStatus:environment.status,temporaryWorkspace}));process.exitCode=2;}
