import assert from "node:assert/strict";
import test from "node:test";
import { createFakeTransport } from "../src/fake-transport.mjs";
import { fixture, rejectionCode } from "./helpers.mjs";

test("validation, pre-abort, pending-before-send, and envelope are correct", async () => { const controller = new AbortController(); controller.abort(); const invalid = fixture(); assert.equal(await rejectionCode(invalid.dispatcher.dispatch("", {})), "invalid_request"); assert.equal(await rejectionCode(invalid.dispatcher.dispatch("x", {}, { signal: controller.signal })), "request_aborted"); assert.equal(invalid.transport.sent().length, 0); let synchronous; const transport = createFakeTransport({ onSend(command, channel) { channel.emitMessage({ type: `${command.type}.completed`, requestId: command.requestId, result: 42 }); } }); const f = fixture({ transport }); synchronous = await f.dispatcher.dispatch("compute", { value: 21 }); assert.equal(synchronous, 42); assert.deepEqual(transport.sent()[0], { type: "compute", requestId: "r1", payload: { value: 21 } }); assert.equal(f.dispatcher.pendingCount, 0); f.dispatcher.dispose(); });
test("concurrent replies resolve out of order without cross-settlement", async () => { const f = fixture(); const one = f.dispatcher.dispatch("work", { value: 1 }); const two = f.dispatcher.dispatch("work", { value: 2 }); const three = f.dispatcher.dispatch("work", { value: 3 }); f.transport.emitMessage({ type: "work.completed", requestId: "r3", result: 30 }); f.transport.emitMessage({ type: "unknown", requestId: "r2", result: -1 }); f.transport.emitMessage({ type: "work.completed", requestId: "missing", result: -1 }); f.transport.emitMessage({ type: "work.completed", requestId: "r1", result: 10 }); f.transport.emitMessage({ type: "work.completed", requestId: "r2", result: 20 }); assert.deepEqual(await Promise.all([one, two, three]), [10, 20, 30]); f.transport.emitMessage({ type: "work.completed", requestId: "r1", result: 99 }); assert.equal(f.dispatcher.pendingCount, 0); f.dispatcher.dispose(); });
test("remote and send failures are stable and sanitized", async () => { const f = fixture(); const remote = f.dispatcher.dispatch("work", {}); f.transport.emitMessage({ type: "work.failed", requestId: "r1", error: { message: "database secret" } }); assert.equal(await rejectionCode(remote), "remote_failure"); const sync = fixture({ transport: createFakeTransport({ onSend() { throw new Error("socket secret"); } }) }); assert.equal(await rejectionCode(sync.dispatcher.dispatch("work", {})), "send_failed"); const asyncFailure = fixture({ transport: createFakeTransport({ onSend() { return Promise.reject(new Error("async secret")); } }) }); assert.equal(await rejectionCode(asyncFailure.dispatcher.dispatch("work", {})), "send_failed"); for (const item of [f, sync, asyncFailure]) { assert.equal(item.dispatcher.pendingCount, 0); item.dispatcher.dispose(); } });
test("timeout and abort settle once and clean pending state", async () => { const f = fixture({ defaultTimeoutMs: 10 }); assert.equal(await rejectionCode(f.dispatcher.dispatch("slow", {})), "request_timeout"); const controller = new AbortController(); const aborted = f.dispatcher.dispatch("slow", {}, { signal: controller.signal, timeoutMs: 100 }); controller.abort(); assert.equal(await rejectionCode(aborted), "request_aborted"); f.transport.emitMessage({ type: "slow.completed", requestId: "r2", result: "late" }); assert.equal(f.dispatcher.pendingCount, 0); f.dispatcher.dispose(); });
test("transport close and disposal reject all, unsubscribe, and isolate instances", async () => { const one = fixture(); const two = fixture(); const a = one.dispatcher.dispatch("work", {}); const b = one.dispatcher.dispatch("work", {}); one.transport.emitClose(); assert.deepEqual(await Promise.all([rejectionCode(a), rejectionCode(b)]), ["transport_closed", "transport_closed"]); const c = two.dispatcher.dispatch("work", {}); two.dispatcher.dispose(); assert.equal(await rejectionCode(c), "dispatcher_disposed"); assert.equal(await rejectionCode(two.dispatcher.dispatch("later", {})), "dispatcher_disposed"); two.dispatcher.dispose(); assert.deepEqual(two.transport.diagnostics(), { messageListeners: 0, closeListeners: 0 }); assert.equal(one.dispatcher.pendingCount, 0); one.dispatcher.dispose(); });
