import { readFile } from "node:fs/promises";
import userEvent from "@testing-library/user-event";
import { expect, it } from "vitest";
import WorkshopDashboard from "../src/WorkshopDashboard.jsx";
import { renderDashboard } from "./helpers.jsx";
it("target preserves filter, selection, validation, capacity, add, and remove behavior", async () => { const user = userEvent.setup(); const view = renderDashboard(WorkshopDashboard); await user.clear(view.getByRole("textbox", { name: "Attendee name" })); await user.click(view.getByRole("button", { name: "Register attendee" })); expect(view.getByRole("alert")).toHaveTextContent("valid seat count"); await user.type(view.getByRole("textbox", { name: "Filter workshops" }), "HTTP"); expect(view.getByRole("heading", { name: "HTTP APIs" })).toBeInTheDocument(); expect(view.getByRole("status")).toHaveTextContent("1 of 3"); await user.type(view.getByRole("textbox", { name: "Attendee name" }), "Ioana"); await user.clear(view.getByRole("spinbutton")); await user.type(view.getByRole("spinbutton"), "3"); await user.click(view.getByRole("button", { name: "Register attendee" })); expect(view.getByRole("alert")).toHaveTextContent("Not enough"); await user.clear(view.getByRole("spinbutton")); await user.type(view.getByRole("spinbutton"), "2"); await user.click(view.getByRole("button", { name: "Register attendee" })); expect(view.getByRole("rowheader", { name: "Ioana" })).toBeInTheDocument(); expect(view.getByRole("textbox", { name: "Attendee name" })).toHaveValue(""); });
it("target imports the five explicit component responsibilities", async () => { const source = await readFile("src/WorkshopDashboard.jsx", "utf8"); for (const name of ["WorkshopToolbar", "CapacitySummary", "RegistrationForm", "AttendeeList"]) expect(source).toContain(name); const list = await readFile("src/components/AttendeeList.jsx", "utf8"); expect(list).toContain("AttendeeRow"); });
it("workshop state survives switching and recomputes capacity", async () => { const user = userEvent.setup(); const view = renderDashboard(WorkshopDashboard); await user.type(view.getByRole("textbox", { name: "Attendee name" }), "Zoe"); await user.click(view.getByRole("button", { name: "Register attendee" })); await user.selectOptions(view.getByRole("combobox"), "http"); expect(view.getByRole("status")).toHaveTextContent("1 of 3"); await user.selectOptions(view.getByRole("combobox"), "react"); expect(view.getByRole("rowheader", { name: "Zoe" })).toBeInTheDocument(); });
it("target avoids derived-state effects and heavyweight abstractions", async () => { const files = ["src/WorkshopDashboard.jsx", "src/components/WorkshopToolbar.jsx", "src/components/CapacitySummary.jsx", "src/components/RegistrationForm.jsx", "src/components/AttendeeList.jsx", "src/components/AttendeeRow.jsx"]; const source = (await Promise.all(files.map((file) => readFile(file, "utf8")))).join("\n"); expect(source).not.toMatch(/useEffect|useMemo|useContext|useReducer|\.push\(|\.splice\(|\.\.\.props|from ["']\.\.\/fixtures/); });
