import {spawn,spawnSync} from 'node:child_process';import{mkdtempSync,rmSync,existsSync}from'node:fs';import{tmpdir}from'node:os';import{join}from'node:path';
// POSIX commands own a new process group. Windows timeout uses only the created PID tree.
export function runOwnedProcess(executable,args,{cwd,env=process.env,timeoutMs=30000,maxBytes=1000000}={}){
 function limit(name,fallback,min,max){const value=env[name];if(value===undefined)return fallback;if(typeof value!=='string'||!/^\d+$/.test(value)||!Number.isSafeInteger(Number(value))||Number(value)<min||Number(value)>max)throw Error('INVALID_'+name);return Number(value);}
 try{timeoutMs=limit('WEBTECH_CHILD_TIMEOUT_MS',timeoutMs,10,60000);maxBytes=limit('WEBTECH_CHILD_MAX_BYTES',maxBytes,1024,10000000);}catch(error){console.error(JSON.stringify({status:'ENV_BLOCKED_WORKER_LIMIT',reason:error.message,allowed:{WEBTECH_CHILD_TIMEOUT_MS:[10,60000],WEBTECH_CHILD_MAX_BYTES:[1024,10000000]},remedy:'Remove or correct only the named local override and rerun the same command; no child has started.'}));return Promise.resolve({ok:false,exitCode:2,signal:null,reason:error.message,stdout:'',stderr:'',argv:[executable,...args],cwd,limits:{timeoutMs,maxBytes},temporaryWorkspace:null,processOwnership:'NO_CHILD_STARTED',treeCleanup:'NOT_NEEDED'});}
 return new Promise(resolve=>{const directory=mkdtempSync(join(tmpdir(),'webtech-owned-worker-'));let child,stdout='',stderr='',bytes=0,reason=null,timer,finished=false,treeCleanup='NOT_NEEDED';
 const stop=why=>{reason??=why;if(!child?.pid)return;if(process.platform==='win32'){const result=spawnSync('taskkill',['/PID',String(child.pid),'/T','/F'],{shell:false,encoding:'utf8',timeout:5000,maxBuffer:65536});treeCleanup=result.status===0?'OWNED_PID_TREE_STOP_REQUESTED':'OWNED_PID_TREE_UNCONFIRMED';if(result.status!==0){reason='WINDOWS_OWNED_TREE_CLEANUP_UNCONFIRMED';child.kill('SIGKILL');}}else{try{process.kill(-child.pid,'SIGKILL');treeCleanup='OWNED_PROCESS_GROUP_STOP_REQUESTED';}catch(error){if(error.code!=='ESRCH'){reason='OWNED_PROCESS_GROUP_CLEANUP_FAILED';treeCleanup=error.code;}}}};
 const finish=(code,signal)=>{if(finished)return;finished=true;clearTimeout(timer);let cleanup='REMOVED_AFTER_OWNED_PROCESS_STOP';try{rmSync(directory,{recursive:true,force:true});}catch(error){reason='OWNED_TEMP_CLEANUP_FAILED';cleanup=error.code;}resolve({ok:!reason&&code===0&&!signal,exitCode:code,signal,reason,stdout,stderr,argv:[executable,...args],cwd,limits:{timeoutMs,maxBytes},temporaryWorkspace:{directory,parentOwned:true,cleanup,directoryExists:existsSync(directory)},processOwnership:process.platform==='win32'?'DIRECT_CHILD_AND_TIMEOUT_OWN_PID_TREE_UNQUALIFIED_NATIVE':'OWN_NEW_POSIX_PROCESS_GROUP',treeCleanup});};
 try{child=spawn(executable,args,{cwd,env:{...env,TMPDIR:directory,TMP:directory,TEMP:directory},detached:process.platform!=='win32',shell:false,stdio:['ignore','pipe','pipe']});}catch(error){reason=error.code||'SPAWN_FAILED';finish(null,null);return;}
 timer=setTimeout(()=>stop('PROCESS_TIMEOUT'),timeoutMs);for(const [stream,key]of[[child.stdout,'stdout'],[child.stderr,'stderr']])stream.on('data',chunk=>{bytes+=chunk.length;if(bytes>maxBytes){stop('OUTPUT_LIMIT');return;}if(key==='stdout')stdout+=chunk;else stderr+=chunk;});child.once('error',error=>{reason=error.code||'SPAWN_FAILED';if(!child.pid)finish(null,null);else stop(reason);});child.once('exit',()=>{if(process.platform!=='win32'){try{process.kill(-child.pid,'SIGKILL');treeCleanup='OWNED_PROCESS_GROUP_CLOSED';}catch(error){if(error.code!=='ESRCH')reason='OWNED_PROCESS_GROUP_CLEANUP_FAILED';}}});child.once('close',finish);
 });
}
