/** Exact package set and protected project-byte checks. Integrity is not a digital signature. */
import {readFile,readdir,lstat,realpath} from 'node:fs/promises';import {join,resolve,dirname} from 'node:path';import {fileURLToPath} from 'node:url';import {createHash} from 'node:crypto';
export const ROOT=resolve(dirname(fileURLToPath(import.meta.url)),'..');export const sha=data=>createHash('sha256').update(data).digest('hex');
export function safeRelative(path){return typeof path==='string'&&path.length>0&&!/[\\:?*<>"|\x00-\x1f\x7f]/.test(path)&&!path.startsWith('/')&&path.split('/').every(x=>x&&x!=='.'&&x!=='..'&&!/[. ]$/.test(x)&&!/^(?:CON|PRN|AUX|NUL|CONIN\$|CONOUT\$|COM[1-9¹²³]|LPT[1-9¹²³])(?:\.|$)/i.test(x));}
async function protectedDirectory(root,relative){if(!safeRelative(relative))throw Error('Unsafe project root');if((await lstat(root)).isSymbolicLink())throw Error('Package root symlink');const realRoot=await realpath(root);let cursor=realRoot;for(const segment of relative.split('/')){cursor=join(cursor,segment);if((await lstat(cursor)).isSymbolicLink())throw Error('Project root ancestor symlink '+segment);if(await realpath(cursor)!==resolve(cursor))throw Error('Project root ancestor does not resolve literally '+segment);}return cursor;}
async function walk(root,{skipDependencies=false}={}){const files=[],errors=[];async function visit(dir,rel=''){for(const d of await readdir(dir,{withFileTypes:true})){const r=rel?rel+'/'+d.name:d.name,p=join(dir,d.name);if(d.isSymbolicLink()){errors.push('Symlink '+r);continue;}if(skipDependencies&&!rel&&d.name==='node_modules'){if(!d.isDirectory())errors.push('Invalid node_modules');continue;}if(d.isDirectory())await visit(p,r);else if(d.isFile())files.push(r);else errors.push('Nonregular '+r);}}try{if((await lstat(root)).isSymbolicLink())throw Error('Root symlink');await visit(root);}catch(e){errors.push('Unreadable root: '+e.message);}return {files:files.sort(),errors};}
export async function config(id,root=ROOT){const all=JSON.parse(await readFile(join(root,'tools/PROJECT_CONTRACT.json'),'utf8'));if(!Object.hasOwn(all,id))throw Error('Unknown project; use p02, p01, p03 or lifecycle');const c=all[id];if(!safeRelative(c.root)||!c.files||Object.keys(c.files).some(p=>!safeRelative(p))||c.target&&(!safeRelative(c.target)||!Object.hasOwn(c.files,c.target)))throw Error('Invalid protected contract');return c;}
export async function boundary(id,root=ROOT){const c=await config(id,root);let directory;try{directory=await protectedDirectory(root,c.root);}catch(e){return {project:id,ok:false,errors:[e.message],files:0,allowedTarget:c.target??null,targetSha256:null,untouched:false,scope:'PROTECTED_BYTE_BOUNDARY_NOT_SEMANTIC_CODE_REVIEW'};}const found=await walk(directory,{skipDependencies:true}),errors=[...found.errors];let targetSha256=null;
 for(const p of found.files){if(!Object.hasOwn(c.files,p)){errors.push('Extra '+p);continue;}const digest=sha(await readFile(join(directory,p)));if(p===c.target)targetSha256=digest;else if(digest!==c.files[p])errors.push('Changed '+p);}
 for(const p of Object.keys(c.files))if(!found.files.includes(p))errors.push('Missing '+p);return {project:id,ok:!errors.length,errors,files:found.files.length,allowedTarget:c.target??null,targetSha256,untouched:c.target?targetSha256===c.files[c.target]:null,scope:'PROTECTED_BYTE_BOUNDARY_NOT_SEMANTIC_CODE_REVIEW'};
}
export async function verifyPackage(root=ROOT){const errors=[];let manifest,id;try{manifest=await readFile(join(root,'SHA256SUMS.txt'));id=await readFile(join(root,'PACKAGE_ID.txt'),'utf8');}catch(e){return {ok:false,status:'BLOCKED',errors:['Missing package identity: '+e.code]};}
 const text=manifest.toString('utf8');if(!text.endsWith('\n')||text.includes('\r')||Buffer.from(text).compare(manifest)!==0)errors.push('Manifest must be exact UTF-8 and LF terminated');const rows=[],seen=new Set(),collisions=new Set(),prefixes=new Map();
 for(const line of text.split('\n').slice(0,-1)){const m=line.match(/^([0-9a-f]{64})  (.+)$/);if(!m||!safeRelative(m?.[2])||['SHA256SUMS.txt','PACKAGE_ID.txt'].includes(m?.[2])){errors.push('Unsafe or malformed manifest row');continue;}if(seen.has(m[2]))errors.push('Duplicate manifest path '+m[2]);seen.add(m[2]);const key=m[2].normalize('NFC').toLowerCase();if(collisions.has(key))errors.push('Case/Unicode collision '+m[2]);collisions.add(key);const parts=m[2].split('/');for(let n=1;n<=parts.length;n++){const literal=parts.slice(0,n).join('/'),normalised=literal.normalize('NFC').toLowerCase();if(prefixes.has(normalised)&&prefixes.get(normalised)!==literal)errors.push('Case/Unicode prefix collision '+literal);else prefixes.set(normalised,literal);}rows.push({path:m[2],hash:m[1]});}
 if(rows.map(r=>r.path).join('\n')!==rows.map(r=>r.path).sort().join('\n'))errors.push('Manifest not sorted by path');if(!/^[0-9a-f]{64}\n$/.test(id)||id.trim()!==sha(manifest))errors.push('PACKAGE_ID does not hash exact manifest bytes');
 const found=await walk(root);errors.push(...found.errors);const expected=[...seen,'PACKAGE_ID.txt','SHA256SUMS.txt'].sort();for(const p of found.files)if(!expected.includes(p))errors.push('Extra '+p);for(const p of expected)if(!found.files.includes(p))errors.push('Missing '+p);for(const row of rows){if(!found.files.includes(row.path))continue;try{if(sha(await readFile(join(root,row.path)))!==row.hash)errors.push('Hash mismatch '+row.path);}catch(e){errors.push('Unreadable '+row.path);}}
 return {ok:!errors.length,status:errors.length?'FAIL_CLOSED':'PASS_EXACT_PACKAGE_BYTES',files:rows.length,packageId:id.trim(),errors,limitation:'Clean extracted package only, before learner edits or dependency preparation. Integrity is not evidence authenticity or a signature.'};
}
