import assert from "node:assert/strict";
import test from "node:test";
import { fixture, code } from "./helpers.mjs";

test("uncontrolled and non-target requests use explicit direct fallback", async () => { const f = fixture({ controlled: false }); assert.equal((await f.dispatcher.request("/api/tasks/t1")).via, "direct"); assert.equal((await f.dispatcher.request("https://other.example/api/tasks/t1")).via, "direct"); assert.equal((await f.dispatcher.request("/api/tasks/t1", { method: "POST" })).via, "direct"); assert.equal(f.container.sent().length, 0); f.dispatcher.dispose(); });
test("controlled request posts after pending registration and correlates exact source/version", async () => { const f = fixture(); const result = f.dispatcher.request("/api/tasks/t1"); result.catch(() => {}); await Promise.resolve(); assert.deepEqual(f.container.sent()[0], { type: "task.request", version: 1, requestId: "r1", url: "https://course.example/api/tasks/t1" }); f.container.emit("message", { source: {}, data: { type: "task.response", version: 1, requestId: "r1", data: { id: "forged" } } }); f.container.emit("message", { source: f.controller, data: { type: "task.response", version: 2, requestId: "r1", data: { id: "stale" } } }); assert.equal(f.dispatcher.diagnostics.pendingCount, 1); f.container.emit("message", { source: f.controller, data: { type: "task.response", version: 1, requestId: "r1", data: { id: "t1" } } }); assert.deepEqual(await result, { id: "t1", via: "service-worker" }); assert.equal(f.dispatcher.diagnostics.pendingCount, 0); f.dispatcher.dispose(); });
test("unknown, malformed, duplicate, and safe failure messages remain isolated", async () => { const f = fixture(); const result = f.dispatcher.request("/api/tasks/t1"); await Promise.resolve(); f.container.emit("message", { source: f.controller, data: null }); f.container.emit("message", { source: f.controller, data: { type: "task.response", version: 1, requestId: "unknown", data: {} } }); f.container.emit("message", { source: f.controller, data: { type: "task.failed", version: 1, requestId: "r1", error: { message: "fetch secret" } } }); assert.equal(await code(result), "task_failed"); f.container.emit("message", { source: f.controller, data: { type: "task.response", version: 1, requestId: "r1", data: {} } }); assert.equal(f.dispatcher.diagnostics.pendingCount, 0); f.dispatcher.dispose(); });
test("timeout falls back once and controller change rejects pending generation", async () => { const f = fixture({ defaultTimeoutMs: 5 }); assert.equal((await f.dispatcher.request("/api/tasks/t1")).via, "direct"); assert.equal(f.directCalls.length, 1); const other = fixture(); const pending = other.dispatcher.request("/api/tasks/t2"); await Promise.resolve(); other.container.emit("controllerchange"); assert.equal(await code(pending), "controller_changed"); assert.equal(other.dispatcher.diagnostics.pendingCount, 0); f.dispatcher.dispose(); other.dispatcher.dispose(); });
test("disposal rejects pending, removes listeners, and prevents later dispatch", async () => { const f = fixture(); const pending = f.dispatcher.request("/api/tasks/t1"); await Promise.resolve(); f.dispatcher.dispose(); assert.equal(await code(pending), "dispatcher_disposed"); assert.equal(await code(f.dispatcher.request("/api/tasks/t1")), "dispatcher_disposed"); assert.deepEqual(f.container.diagnostics(), { message: 0, controllerchange: 0 }); f.dispatcher.dispose(); });
