import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
const html = await readFile(new URL("./index.html", import.meta.url), "utf8");
assert.match(html, /<html lang="en-GB">/);
assert.match(html, /<label for="email">Email address<\/label>/);
assert.match(html, /id="email"[^>]*type="email"[^>]*required[^>]*aria-describedby="email-help"/);
assert.match(html, /<span id="email-help">/);
assert.match(html, /<fieldset>[\s\S]*<legend>Attendance mode<\/legend>/);
assert.match(html, /<button type="submit">Register<\/button>/);
assert.match(html, /<label for="email-invalid">/);
assert.match(html, /id="email-invalid"[^>]*type="email"[^>]*required[^>]*aria-invalid="true"[^>]*aria-describedby="email-invalid-help email-error"/);
assert.match(html, /<p id="email-error" class="error">Enter an email address/);
assert.match(html, /id="show-invalid"/);
assert.match(html, /id="show-valid"/);
console.log("PASS_FORM_SOURCE_RELATIONSHIPS — static checks only; inspect keyboard and error-state behaviour in a browser");
