import{createRequire}from'node:module';import{join}from'node:path';import{pathToFileURL}from'node:url';import{createServer}from'node:http';
const[root,profile,...extra]=process.argv.slice(2),require=createRequire(join(root,'package.json'));let server,wss,client,db,statement,timer;const sockets=new Set();
try{if(!root||extra.length||!['express','express-sqljs','express-ws','ws','node-review'].includes(profile))throw Error('UNAVAILABLE_SELECTED_API_PROFILE');
 if(profile==='node-review'){const review=await import(pathToFileURL(join(root,'review.mjs')));if(typeof review.collectEvidence!=='function'||typeof review.gate!=='function')throw Error('REVIEW_API_MISSING');const rows=review.collectEvidence();if(!Array.isArray(rows)||!rows.some(row=>row.name==='syntax'&&row.state==='pass')||!rows.some(row=>row.name==='dependency-audit'&&row.state==='unknown'))throw Error('REVIEW_COMMAND_OPERATION_FAILED');}
 if(profile.startsWith('express')){const express=require('express');if(typeof express!=='function'||typeof express.json!=='function')throw Error('EXPRESS_API_MISSING');const app=express();if(typeof app.get!=='function'||typeof app.use!=='function')throw Error('EXPRESS_APP_API_MISSING');app.get('/owned-probe',(_req,res)=>res.json({owned:'probe'}));server=createServer(app);server.on('connection',socket=>{sockets.add(socket);socket.once('close',()=>sockets.delete(socket));});await new Promise((resolve,reject)=>{server.once('error',reject);server.listen(0,'127.0.0.1',resolve);});const control=new AbortController();timer=setTimeout(()=>control.abort(),3500);const response=await fetch('http://127.0.0.1:'+server.address().port+'/owned-probe',{signal:control.signal});if(response.status!==200||(await response.json()).owned!=='probe')throw Error('EXPRESS_HTTP_OPERATION_FAILED');clearTimeout(timer);}
 if(profile==='express-sqljs'){const init=require('sql.js');if(typeof init!=='function')throw Error('SQLJS_INIT_API_MISSING');const SQL=await init();if(typeof SQL.Database!=='function')throw Error('SQLJS_DATABASE_API_MISSING');db=new SQL.Database();for(const name of['run','prepare','close'])if(typeof db[name]!=='function')throw Error('SQLJS_DATABASE_API_MISSING '+name);db.run("CREATE TABLE own_probe(value TEXT); INSERT INTO own_probe VALUES ('probe')");statement=db.prepare('SELECT value FROM own_probe WHERE value = ?');for(const name of['bind','step','getAsObject','free'])if(typeof statement[name]!=='function')throw Error('SQLJS_STATEMENT_API_MISSING '+name);statement.bind(['probe']);if(!statement.step()||statement.getAsObject().value!=='probe'||statement.step())throw Error('SQLJS_BOUND_OPERATION_FAILED');statement.free();statement=null;db.close();db=null;}
 if(profile.endsWith('ws')){const ws=require('ws');if(typeof ws.WebSocketServer!=='function'||typeof ws.WebSocket!=='function')throw Error('WEBSOCKET_API_MISSING');wss=new ws.WebSocketServer({host:'127.0.0.1',port:0});await new Promise((resolve,reject)=>{wss.once('listening',resolve);wss.once('error',reject);});wss.on('connection',socket=>socket.once('message',value=>socket.send(value)));client=new ws.WebSocket('ws://127.0.0.1:'+wss.address().port);await new Promise((resolve,reject)=>{client.once('open',resolve);client.once('error',reject);});const received=new Promise((resolve,reject)=>{client.once('message',value=>resolve(String(value)));client.once('error',reject);});client.send('owned-ws-probe');if(await received!=='owned-ws-probe')throw Error('WEBSOCKET_ROUNDTRIP_FAILED');}
 console.log(JSON.stringify({status:'ENV_OK',operation:'Actual selected '+profile+' library operation with owned ephemeral resources and cleanup; no authentication/browser/queue inference'}));
}catch(error){console.log(JSON.stringify({status:'ENV_BLOCKED',reason:error.code||error.message}));process.exitCode=2;}
finally{clearTimeout(timer);const cleanupFailures=[];async function cleanup(operation){try{await operation();}catch(error){cleanupFailures.push(error.code||error.message);}}
 await cleanup(()=>statement?.free());await cleanup(()=>db?.close());await cleanup(()=>client?.terminate());
 if(wss){for(const socket of wss.clients)await cleanup(()=>socket.terminate());await cleanup(()=>new Promise((resolve,reject)=>wss.close(error=>error?reject(error):resolve())));}
 for(const socket of sockets)await cleanup(()=>socket.destroy());if(server)await cleanup(()=>new Promise((resolve,reject)=>server.close(error=>error&&error.code!=='ERR_SERVER_NOT_RUNNING'?reject(error):resolve())));
 if(cleanupFailures.length){console.error(JSON.stringify({status:'ENV_BLOCKED',reason:'OWNED_API_RESOURCE_CLEANUP_FAILED',cleanupFailures}));process.exitCode=2;}}
