/** Read-only, fixed-scenario client for an explicitly started local teaching API. */
import http from 'node:http';import {resolve} from 'node:path';import {fileURLToPath} from 'node:url';
export const scenarios=Object.freeze({health:'/health',default:'/api/notes',combined:'/api/notes?owner=Ada&archived=false&sort=title_asc&fields=title%2Cowner',literal:'/api/notes?search=%25',ascii:'/api/notes?search=alpha&sort=title_asc',updated_desc:'/api/notes?sort=updated_desc',updated_asc:'/api/notes?sort=updated_asc',title_asc:'/api/notes?sort=title_asc',projection:'/api/notes?fields=title%2Cowner&sort=title_asc',invalid:'/api/notes?archived=yes',repeated:'/api/notes?owner=Ada&owner=Grace',unknown:'/api/notes?unlisted=x'});
export function origin(value){if(typeof value!=='string'||!/^http:\/\/127\.0\.0\.1:[1-9][0-9]{0,4}$/.test(value)||Number(value.split(':').pop())>65535)throw Error('Use exactly http://127.0.0.1:PORT from READY');return value;}
export function request(base,id,{timeout=5000,maxBytes=65536}={}){
 origin(base);if(!Object.hasOwn(scenarios,id))throw Error('Unknown fixed scenario');if(!Number.isInteger(timeout)||timeout<1||timeout>10000||!Number.isInteger(maxBytes)||maxBytes<1||maxBytes>1000000)throw Error('Invalid response bound');
 return new Promise((ok,bad)=>{let done=false,timer;const finish=(err,value)=>{if(done)return;done=true;clearTimeout(timer);err?bad(err):ok(value);};const chunks=[];let bytes=0;
  const req=http.get(base+scenarios[id],res=>{res.on('data',d=>{bytes+=d.length;if(bytes>maxBytes){finish(Error('RESPONSE_TOO_LARGE'));req.destroy();res.destroy();}else chunks.push(d);});res.on('error',e=>finish(e));res.on('aborted',()=>finish(Error('RESPONSE_ABORTED')));res.on('end',()=>{const text=Buffer.concat(chunks).toString('utf8');let json=null;try{json=JSON.parse(text);}catch(_){}finish(null,{scenario:id,method:'GET',path:scenarios[id],status:res.statusCode,headers:{'content-type':res.headers['content-type']??null,location:res.headers.location??null},body:text,json,bodyBytes:bytes,evidenceClass:'LOCAL_HTTP_OBSERVATION',evaluated:false,redirectFollowed:false});});});
  req.on('error',e=>finish(e));timer=setTimeout(()=>{finish(Error('REQUEST_TIMEOUT'));req.destroy();},timeout);
 });
}
export function evaluate(observation){const {scenario:id,json,status}=observation,checks=[];const add=(name,ok)=>checks.push({name,ok:!!ok});
 if(['invalid','repeated','unknown'].includes(id)){add('status 400',status===400);add('stable public error',json?.error?.code==='invalid_query');}
 else if(id==='health')add('healthy response',status===200&&json?.status==='ok');
 else {add('status 200 and data array',status===200&&Array.isArray(json?.data));const rows=Array.isArray(json?.data)?json.data:[];const expected={default:[4,1,2,3],combined:[1],literal:[2],ascii:[1,3],updated_desc:[4,1,2,3],updated_asc:[3,1,2,4],title_asc:[2,1,3,4],projection:[2,1,3,4]};if(expected[id])add('IDs in documented fixture order',JSON.stringify(rows.map(x=>x?.id))===JSON.stringify(expected[id]));if(['combined','projection'].includes(id))add('only id/title/owner',rows.length>0&&rows.every(x=>JSON.stringify(Object.keys(x).sort())===JSON.stringify(['id','owner','title'])));}
 return {...observation,evaluated:true,checks,ok:checks.length>0&&checks.every(c=>c.ok),limitation:'Fixture comparison only. This cannot identify the server implementation or prove zero findAll calls.'};
}
export async function series(base,name,options){const ids=name==='all'?Object.keys(scenarios):name==='recovery'?['invalid','default','health']:[name];const observations=[];for(const id of ids){try{observations.push(evaluate(await request(base,id,options)));}catch(e){return {ok:false,stoppedAt:id,error:e.message,observations,qualification:'LOCAL_CLIENT_ONLY'};}}return {ok:observations.every(x=>x.ok),observations,qualification:'LOCAL_CLIENT_ONLY'};}
export async function main(args=process.argv.slice(2)){const [base,name,...tail]=args;if(tail.length)throw Error('Use ORIGIN SCENARIO (or all/recovery); no extra arguments');origin(base);if(!['all','recovery'].includes(name)&&!Object.hasOwn(scenarios,name))throw Error('Unknown scenario');const result=await series(base,name);console.log(JSON.stringify(result,null,2));return result.ok?0:1;}
if(process.argv[1]&&resolve(process.argv[1])===fileURLToPath(import.meta.url))main().then(c=>process.exitCode=c).catch(e=>{console.error('PROBE_FAILED: '+e.message);process.exitCode=2;});
