/** Internal derived worker. Invoke root launchers: the parent owns deadlines and classification. */
import {join} from 'node:path';import {pathToFileURL} from 'node:url';import {createRequire} from 'node:module';import {createServer} from 'node:http';import {mkdtemp,rm,readFile} from 'node:fs/promises';import {tmpdir} from 'node:os';import {randomUUID} from 'node:crypto';import {inspect} from 'node:util';
import {ROOT,config,boundary} from './integrity.mjs';import {environment,requireReady,REQUIRED_NODE} from './environment.mjs';
async function prerequisite(id){const edge=await boundary(id);if(!edge.ok)throw Error('EDIT_BOUNDARY_BLOCKED');requireReady(await environment(id));}
async function imports(id){const c=await config(id),root=join(ROOT,c.root);return {root,req:createRequire(join(root,'package.json'))};}
export async function closeDatabase(database,operation){let value,error;try{value=await operation(database);}catch(e){error=e;}try{await database.sequelize.close();}catch(e){error=error?new AggregateError([error,e],'Operation and database closure failed'):e;}if(error)throw error;return value;}
export async function listenOwned(handler,port=0){const server=createServer(handler);await new Promise((ok,bad)=>{server.once('error',bad);server.listen(port,'127.0.0.1',()=>{server.off('error',bad);ok();});});return {server,origin:`http://127.0.0.1:${server.address().port}`};}
async function closeServer(server){server.closeIdleConnections?.();await new Promise((ok,bad)=>server.close(e=>e?bad(e):ok()));}
async function nativeLoad(id){if(!(await boundary(id)).ok)throw Error('EDIT_BOUNDARY_BLOCKED');if(process.version!==REQUIRED_NODE)throw Error('REFERENCE_NODE_BLOCKED');const {req}=await imports(id);req('sqlite3');console.log(JSON.stringify({status:'NATIVE_SQLITE3_MODULE_LOADED',databaseOpened:false,qualification:'MODULE_LOAD_ONLY_NOT_ORM_OR_SQL_EXECUTION'}));}
async function observeQuery(){await prerequisite('p02');const {root}=await imports('p02'),query=await import(pathToFileURL(join(root,'src/note-query.js'))),db=await import(pathToFileURL(join(root,'src/database.js')));const database=db.createDatabase();return closeDatabase(database,async()=>{await db.initializeDatabase(database);const input=Object.freeze({owner:' Ada ',archived:'false',sort:'title_asc',fields:'title,owner'}),before=JSON.stringify(input);const first=query.buildNoteQuery(input),second=query.buildNoteQuery(input);let calls=0;const find=database.Note.findAll.bind(database.Note);database.Note.findAll=(...args)=>{calls++;return find(...args);};const rows=(await database.Note.findAll(first)).map(n=>n.get({plain:true}));const prior=calls;let rejected=null;try{await database.Note.findAll(query.buildNoteQuery({archived:'yes'}));}catch(e){rejected={name:e.name,code:e.code,queryValidationError:e instanceof query.QueryValidationError};}
 const fresh={inputUnchanged:JSON.stringify(input)===before,optionsDistinct:first!==second,orderDistinct:first.order!==second.order,firstPairDistinct:first.order?.[0]!==second.order?.[0]};const checks={combinedIds:JSON.stringify(rows.map(r=>r.id))==='[1]',projectedFields:rows.length===1&&JSON.stringify(Object.keys(rows[0]).sort())==='["id","owner","title"]',invalidRejected:rejected?.queryValidationError===true&&rejected.code==='invalid_query',zeroInvalidModelCalls:calls-prior===0,...fresh};return {evidenceClass:'ACTUAL_ORM_SQLITE_MODULE_MODEL_WITNESS',storage:':memory:',rows,input,options:inspect(first,{depth:8}),invalidBeforeModel:{rejected,calls:calls-prior},fresh,checks,ok:Object.values(checks).every(Boolean),cleanup:'DATABASE_CONNECTION_CLOSED_BEFORE_PARENT_RECEIVES_SUCCESS',limitation:'Module/model evidence. Express route call count requires the separate canonical objective spy; this does not prove durable file persistence.'};});}
async function lifecycle(){await prerequisite('lifecycle');const {req}=await imports('lifecycle');const sqlite=req('sqlite3'),{Sequelize,DataTypes}=req('sequelize'),directory=await mkdtemp(join(tmpdir(),'tw-s06-lifecycle-')),storage=join(directory,'notes.sqlite'),marker='S06-'+randomUUID();console.error('[OWNED_TEMPORARY_DIRECTORY] '+directory);let mayRemove=true,result,error;const stages=[];
 async function stage(label,reset,insert){const sequelize=new Sequelize({dialect:'sqlite',storage,logging:false,dialectModule:sqlite});let failure;try{const Note=sequelize.define('CourseNote',{title:{type:DataTypes.STRING,allowNull:false,unique:true}},{tableName:'course_notes',timestamps:false});await sequelize.sync(reset?{force:true}:undefined);if(await Note.count()===0)await Note.create({title:'Seeded once'});if(insert)await Note.create({title:marker});stages.push({label,reset,pid:process.pid,rows:await Note.findAll({order:[['id','ASC']],raw:true})});}catch(e){failure=e;}try{await sequelize.close();}catch(e){mayRemove=false;failure=failure?new AggregateError([failure,e],'Operation and closure failed'):e;}if(failure)throw failure;}
 try{await stage('create',false,true);await stage('reopen',false,false);await stage('explicit_reset',true,false);const signature=(await readFile(storage)).subarray(0,16).toString('latin1');const checks={markerSurvived:stages[1].rows.some(r=>r.title===marker),resetRemovedMarker:!stages[2].rows.some(r=>r.title===marker),sqliteSignature:signature==='SQLite format 3\0'};result={stages,checks,signature,ok:Object.values(checks).every(Boolean)};}catch(e){error=e;}
 let cleanup='KEPT_AFTER_DATABASE_CLOSE_FAILURE';if(mayRemove)try{await rm(directory,{recursive:true,force:true});cleanup='OWNED_DIRECTORY_REMOVED';}catch(e){cleanup='CLEANUP_FAILED';error??=e;}
 return {evidenceClass:'ACTUAL_ORM_SQLITE_FILE_LIFECYCLE',boundary:'SAME_PROCESS_CONNECTION_REOPEN',directory,storage,marker,result,error:error?.message??null,cleanup,ok:!error&&result?.ok===true&&cleanup==='OWNED_DIRECTORY_REMOVED',secondProcess:false,powerLossTest:false,limitation:'Minimal course model, not complete P01 or P02 persistence; parent forced termination leaves cleanup UNKNOWN.'};}
async function serve(){if(!process.send)throw Error('Use START launcher; parent IPC ownership required');await prerequisite('p02');const {root}=await imports('p02'),db=await import(pathToFileURL(join(root,'src/database.js'))),{createApp}=await import(pathToFileURL(join(root,'src/app.js')));const database=db.createDatabase();let connection;try{await db.initializeDatabase(database);connection=await listenOwned(createApp({Note:database.Note}));}catch(error){try{await database.sequelize.close();}catch(close){throw new AggregateError([error,close],'Initialisation and cleanup failed');}throw error;}
 let closing=false;async function stop(){if(closing)return;closing=true;let failure;try{await closeServer(connection.server);}catch(e){failure=e;}try{await database.sequelize.close();}catch(e){failure=failure?new AggregateError([failure,e],'Listener and database closure failed'):e;}if(failure){process.send?.({type:'close-failed',message:failure.message});process.exitCode=1;}else process.send?.({type:'closed',listenerClosed:true,databaseClosed:true});if(process.connected)process.disconnect();}
 process.on('message',m=>{if(m?.type==='stop')void stop();});process.once('SIGINT',()=>void stop());process.once('SIGTERM',()=>void stop());process.once('disconnect',()=>void stop());process.send({type:'ready',origin:connection.origin,storage:':memory:'});}
async function main(){const [action,id,...extra]=process.argv.slice(2);if(extra.length)throw Error('Unexpected worker arguments');if(action==='native-load'){if(!['p02','p01','p03','lifecycle'].includes(id))throw Error('Invalid native-load project');await nativeLoad(id);return;}if(id)throw Error('Unexpected worker project argument');if(process.version!==REQUIRED_NODE)throw Error('REFERENCE_NODE_BLOCKED');if(action==='serve'){await serve();return;}const result=action==='observe-query'?await observeQuery():action==='lifecycle'?await lifecycle():null;if(!result)throw Error('Unknown internal worker action');console.log(JSON.stringify(result,null,2));process.exitCode=result.ok?0:1;}
main().catch(e=>{console.error('WORKER_BLOCKED_OR_FAILED: '+e.message);process.exitCode=2;});
