import {REFERENCE} from './environment.mjs';
import {assessActivityEnvironment} from './activity-environment.mjs';
import {runOwnedWorker,assertWorkerCompleted} from './owned-worker.mjs';
import {readFileSync,lstatSync,readdirSync} from 'node:fs';
import {createHash} from 'node:crypto';import {spawnSync} from 'node:child_process';import {fileURLToPath} from 'node:url';import {dirname,join} from 'node:path';
const root=dirname(fileURLToPath(import.meta.url)),config=JSON.parse(readFileSync(join(root,'contract.json'),'utf8'));
const exact=process.version===REFERENCE.node;
function sha(path){const stat=lstatSync(path);if(!stat.isFile()||stat.isSymbolicLink())throw Error('NON_REGULAR_SOURCE '+path);return createHash('sha256').update(readFileSync(path)).digest('hex');}
const [action='help',project='all',...tail]=process.argv.slice(2);if(tail.length||!['initial','check','observe','serve'].includes(action)||!['all',...config.projects.map(p=>p.id)].includes(project)){console.error('Use node CLASSROOM_RC6/kit.mjs initial | check P01/P02/P03/all | observe P01/P02/P03/all | serve');process.exit(2);}
const environment=await assessActivityEnvironment({unit:'S07/'+project,operation:action,cwd:dirname(root),command:'node CLASSROOM_RC6/kit.mjs '+action+' '+project,usesSqlite:action!=='serve'&&['all','P01','P02'].includes(project),usesHttp:action==='serve'||['all','P03'].includes(project),usesHttpTimeout:action!=='serve'&&['all','P03'].includes(project)});console.error(JSON.stringify(environment));if(environment.exitCode)process.exit(environment.exitCode);
let temporaryWorkspace=null;
try{const manifest=JSON.parse(readFileSync(join(root,'SOURCE_MANIFEST.json'),'utf8'));const found=[];function walk(dir,prefix=''){for(const item of readdirSync(dir,{withFileTypes:true})){const p=prefix+item.name;if(item.isDirectory())walk(join(dir,item.name),p+'/');else{if(item.isSymbolicLink()||!item.isFile())throw Error('NON_REGULAR_SOURCE '+p);found.push(p);}}}walk(root);const expected=[...Object.keys(manifest.protected),...Object.keys(manifest.targets),'SOURCE_MANIFEST.json'].sort();if(JSON.stringify(found.sort())!==JSON.stringify(expected))throw Error('CLASSROOM_SOURCE_SET_CHANGED');for(const [p,digest]of Object.entries(manifest.protected))if(sha(join(root,p))!==digest)throw Error('PROTECTED_SOURCE_CHANGED '+p);for(const p of Object.keys(manifest.targets))sha(join(root,p));if(action==='initial')for(const[p,digest]of Object.entries(manifest.targets))if(sha(join(root,p))!==digest)throw Error('INITIAL_REQUIRES_ORIGINAL_STARTERS '+p);
 const before=Object.fromEntries(Object.keys(manifest.targets).map(p=>[p,sha(join(root,p))]));
 if(action==='serve'){const child=await import('./server.mjs');await child.serve();}else{const result=await runOwnedWorker([join(root,'checks.mjs'),action,project],{cwd:root,maxBytes:2000000});temporaryWorkspace=result.temporaryWorkspace;if(result.stderr)process.stderr.write(result.stderr);assertWorkerCompleted(result);let report;try{report=JSON.parse(result.stdout);}catch{throw Error('UNPARSEABLE_WORKER_OUTPUT '+String(result.stderr).slice(0,200));}const after=Object.fromEntries(Object.keys(manifest.targets).map(p=>[p,sha(join(root,p))]));if(JSON.stringify(before)!==JSON.stringify(after))throw Error('TARGET_CHANGED_DURING_CHECK');for(const [p,digest]of Object.entries(manifest.protected))if(sha(join(root,p))!==digest)throw Error('PROTECTED_SOURCE_CHANGED_DURING_CHECK '+p);console.log(JSON.stringify({...report,referenceNode:REFERENCE.node,referenceNodeMatch:exact,environmentStatus:environment.status,temporaryWorkspace,observedNode:process.version,sourceBoundary:'PROTECTED_FILES_AND_STABLE_TARGET_BYTES',nativeQualification:false,completionTimePilot:false,limitation:config.limitation},null,2));process.exitCode=report.cases?.some(item=>item.status==='EXECUTION_FAULT')?2:(result.status??1);}
}catch(error){console.error(JSON.stringify({status:'STOP_CLASSROOM_BOUNDARY_OR_EXECUTION',reason:error.message,referenceNode:REFERENCE.node,referenceNodeMatch:exact,environmentStatus:environment.status,temporaryWorkspace,observedNode:process.version}));process.exitCode=2;}
