import {createRequire} from 'node:module';import {join} from 'node:path';import {pathToFileURL} from 'node:url';
const [root,profile]=process.argv.slice(2),require=createRequire(join(root,'package.json'));let window;
try{const React=require('react'),server=require('react-dom/server');for(const name of ['createElement','useState','useEffect'])if(typeof React[name]!=='function')throw Error('REACT_API_MISSING '+name);if(typeof server.renderToStaticMarkup!=='function')throw Error('REACT_DOM_RENDER_API_MISSING');
 const Component=()=>{const [value]=React.useState('owned-react-probe');return React.createElement('p',null,value);};if(server.renderToStaticMarkup(React.createElement(Component))!=='<p>owned-react-probe</p>')throw Error('REACT_RENDER_OPERATION_FAILED');
 const vite=await import(pathToFileURL(require.resolve('vite')).href);if(typeof vite.build!=='function'||typeof vite.createServer!=='function')throw Error('VITE_API_MISSING');
 const plugin=await import(pathToFileURL(require.resolve('@vitejs/plugin-react')).href);if(typeof plugin.default!=='function')throw Error('VITE_REACT_PLUGIN_API_MISSING');
 if(profile==='seminar'){const {JSDOM}=require('jsdom');if(typeof JSDOM!=='function')throw Error('JSDOM_API_MISSING');window=new JSDOM('<p>owned-dom-probe</p>').window;if(window.document.querySelector('p').textContent!=='owned-dom-probe')throw Error('JSDOM_OPERATION_FAILED');const vitest=await import(pathToFileURL(require.resolve('vitest/node')).href);if(typeof vitest.startVitest!=='function')throw Error('VITEST_NODE_API_MISSING');}
 console.log(JSON.stringify({status:'ENV_OK',operation:'Actual React component/useState SSR, Vite/plugin APIs'+(profile==='seminar'?', owned JSDOM document and Vitest API':''),scope:'Selected import/API/SSR operation only; no learner objective, effect/browser interaction or dependency-tree certification'}));
}catch(error){console.log(JSON.stringify({status:'ENV_BLOCKED',reason:error.code||error.message}));process.exitCode=2;}finally{window?.close();}
