/** C06 bounded local example adapter. No install, download or fallback database. */
import {readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
import {spawnSync} from 'node:child_process';
import {assessOptionalEnvironment} from './optional-environment.mjs';
const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
export const EXAMPLES=Object.freeze({'01':'01-model-metadata','02':'02-initialization-policy','03':'03-await-error-boundary','04':'04-detached-data-boundary','05':'05-query-allowlist'});
export function rootFor(id){if(!Object.keys(EXAMPLES).includes(id))throw new TypeError('Example must be 01, 02, 03, 04 or 05');return path.join(ROOT,'canonical',EXAMPLES[id]);}
export function cleanEnvironment(){const env={...process.env};for(const k of ['NODE_OPTIONS','NODE_PATH','NODE_TEST_CONTEXT'])delete env[k];return env;}
export function sourceBoundary(id){const prefix='canonical/'+EXAMPLES[id]+'/';rootFor(id);const rows=JSON.parse(readFileSync(path.join(ROOT,'CANONICAL_SOURCES.json'),'utf8')).filter(r=>r.path.startsWith(prefix));const errors=[];for(const r of rows){try{const h=createHash('sha256').update(readFileSync(path.join(ROOT,r.path))).digest('hex');if(h!==r.sha256)errors.push('Changed '+r.path);}catch(e){errors.push('Missing '+r.path);}}return {files:rows.length,errors};}
export async function preflight(id){
 const result=await assessOptionalEnvironment({unit:'C06/optional-'+id,operation:'optional-preflight',cwd:ROOT,command:'node tools/examples.mjs preflight '+id,root:rootFor(id),profile:'orm',usesHttp:!['01','02'].includes(id),usesTestRunner:!['01','02'].includes(id),source:sourceBoundary(id)});
 return {example:id,status:result.environment.status,exitCode:result.environment.exitCode,node:process.version,referenceNode:'v24.21.0',referenceNodeMatch:process.version==='v24.21.0',npm:'NOT_REQUIRED_DIRECT_NODE',...result,qualification:'SELECTED_OPTIONAL_API_PROBES_ONLY_NO_REFERENCE_OR_NATIVE_QUALIFICATION'};
}
export async function requireReady(id,compatibility=false){const p=await preflight(id);if(!p.ready){const error=Error('ENV_BLOCKED optional C06 example '+id);error.environment=p.environment;throw error;}return p;}
export function boundedNode(args,cwd,timeout=20000){if(!Array.isArray(args)||args.some(x=>typeof x!=='string'))throw new TypeError('Invalid argument list');const r=spawnSync(process.execPath,args,{cwd,encoding:'utf8',env:cleanEnvironment(),timeout,maxBuffer:1_000_000,killSignal:'SIGKILL'});return {cwd,argv:[process.execPath,...args],timeoutMs:timeout,maxBytes:1_000_000,exit:r.status,signal:r.signal,error:r.error?.code||null,stdout:r.stdout||'',stderr:r.stderr||'',scope:'BOUNDED_DIRECT_CHILD_NOT_A_GENERAL_SANDBOX'};}
export async function runExample(id,{compatibility=false}={}){const p=await requireReady(id,compatibility),file=['01','02'].includes(id)?'example.js':'check.test.js',args=['01','02'].includes(id)?[file]:['--test','--test-isolation=none','--test-reporter=tap',file];const result=boundedNode(args,rootFor(id));return {preflight:p,evidenceClass:'ACTUAL_CANONICAL_EXECUTION_ATTEMPT',nonreference:!p.referenceNodeMatch,result,completedWithoutProcessFault:result.exit===0&&!result.error&&!result.signal,limit:'A zero exit is not full native-platform or reference-runtime acceptance. Review the original assertions and output.'};}
export async function main(argv=process.argv.slice(2)){const [action,id,...flags]=argv;if(!['preflight','run'].includes(action)||flags.some(x=>!['--compatibility','--allow-owned-test-data'].includes(x))||new Set(flags).size!==flags.length)throw new TypeError('Use preflight ID or run ID --allow-owned-test-data [--compatibility]');rootFor(id);if(action==='preflight'){if(flags.length)throw new TypeError('Preflight takes no flags');const result=await preflight(id);console.log(JSON.stringify(result,null,2));return result.exitCode;}if(!flags.includes('--allow-owned-test-data'))throw new Error('Explicit --allow-owned-test-data is required');const r=await runExample(id,{compatibility:flags.includes('--compatibility')});console.log(JSON.stringify(r,null,2));return r.completedWithoutProcessFault?0:1;}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url)){main().then(code=>process.exitCode=code).catch(error=>{console.error(JSON.stringify(error.environment||{status:'STOP_COURSE_COMMAND',reason:error.message,observedNode:process.version,nodeExecutable:process.execPath,observedCwd:process.cwd(),observedArgv:[process.execPath,...process.argv.slice(1)]}));process.exitCode=2;});}
