import React from "react";
import { act, render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { readFile } from "node:fs/promises";
import { expect, it, vi } from "vitest";
import App from "../src/App.jsx";
import { createAppStore } from "../src/store/store.js";
import { markNotificationRead, refreshNotifications, selectMarkStatus, selectNotificationById, selectNotifications, selectRefreshError, selectRefreshStatus, selectUnreadCount } from "../src/store/notifications-slice.js";
import { controlledApi, deferred } from "./helpers.js";

const notes = [{ id: "a", title: "Older", read: false, createdAt: "2026-01-01T00:00:00.000Z" }, { id: "b", title: "Newer", read: true, createdAt: "2026-02-01T00:00:00.000Z" }];
it("normalizes, sorts, and derives authoritative refresh data", async () => { const api = controlledApi(); api.list = vi.fn(async () => structuredClone(notes)); const store = createAppStore({ notificationsApi: api }); await store.dispatch(refreshNotifications()); expect(selectNotifications(store.getState()).map(({ id }) => id)).toEqual(["b", "a"]); expect(selectUnreadCount(store.getState())).toBe(1); expect(selectRefreshStatus(store.getState())).toBe("succeeded"); expect(selectNotificationById(store.getState(), "missing")).toBeUndefined(); });
it("newest refresh wins and failure retains data with stable error", async () => { const first = deferred(); const second = deferred(); const api = controlledApi(); api.list = vi.fn().mockReturnValueOnce(first.promise).mockReturnValueOnce(second.promise).mockRejectedValueOnce(new Error("secret")); const store = createAppStore({ notificationsApi: api }); const old = store.dispatch(refreshNotifications()); const current = store.dispatch(refreshNotifications()); second.resolve([{ id: "new", title: "New", read: false, createdAt: "2026-03-01T00:00:00.000Z" }]); await current; first.resolve([{ id: "old", title: "Old", read: false, createdAt: "2025-01-01T00:00:00.000Z" }]); await old; expect(selectNotifications(store.getState()).map(({ id }) => id)).toEqual(["new"]); await store.dispatch(refreshNotifications()); expect(selectNotifications(store.getState()).map(({ id }) => id)).toEqual(["new"]); expect(selectRefreshError(store.getState())).toBe("Could not refresh notifications"); });
it("mark-read publishes only authoritative success and isolates per-ID failure", async () => { const pending = deferred(); const api = controlledApi(); api.list = async () => structuredClone(notes); api.markRead = vi.fn().mockReturnValueOnce(pending.promise).mockRejectedValueOnce(new Error("secret")); const store = createAppStore({ notificationsApi: api }); await store.dispatch(refreshNotifications()); const marking = store.dispatch(markNotificationRead("a")); expect(selectNotificationById(store.getState(), "a").read).toBe(false); expect(selectMarkStatus(store.getState(), "a").status).toBe("loading"); pending.resolve({ ...notes[0], title: "Server normalized", read: true }); await marking; expect(selectNotificationById(store.getState(), "a").title).toBe("Server normalized"); await store.dispatch(markNotificationRead("b")); expect(selectNotificationById(store.getState(), "b").read).toBe(true); expect(selectMarkStatus(store.getState(), "b")).toEqual({ status: "failed", error: "Could not mark notification as read" }); });
it("header, list, route detail, and confirmed mark stay synchronized", async () => { const api = controlledApi(); api.list = async () => structuredClone(notes); api.markRead = async (id) => ({ ...notes.find((item) => item.id === id), read: true }); const store = createAppStore({ notificationsApi: api }); render(<App store={store} />); expect(await screen.findByRole("link", { name: "Older" })).toBeInTheDocument(); expect(screen.getByLabelText("Unread notifications")).toHaveTextContent("Unread: 1"); await userEvent.click(screen.getByRole("link", { name: "Older" })); await userEvent.click(screen.getByRole("button", { name: "Mark as read" })); expect(await screen.findByText("Read")).toBeInTheDocument(); expect(screen.getByLabelText("Unread notifications")).toHaveTextContent("Unread: 0"); });
it("stores with different injected APIs remain isolated and source stays Toolkit-only", async () => { const one = controlledApi(); one.list = async () => [notes[0]]; const two = controlledApi(); two.list = async () => [notes[1]]; const storeOne = createAppStore({ notificationsApi: one }); const storeTwo = createAppStore({ notificationsApi: two }); await Promise.all([storeOne.dispatch(refreshNotifications()), storeTwo.dispatch(refreshNotifications())]); expect(selectNotifications(storeOne.getState())[0].id).toBe("a"); expect(selectNotifications(storeTwo.getState())[0].id).toBe("b"); const source = await readFile("src/store/notifications-slice.js", "utf8"); expect(source).toMatch(/createEntityAdapter/); expect(source).toMatch(/createAsyncThunk/); expect(source).not.toMatch(/fetch\(|createStore|redux-promise|window\.|currentRoute|selectedRoute|listFilter/i); });
