// Derived initial-state obligations. Original canonical objectives remain unchanged.
import assert from "node:assert/strict";
import test from "node:test";
import { createFakeTransport } from "../src/fake-transport.mjs";
import { fixture, observed, signalModel } from "./fixture.mjs";
test("INITIAL O1 validates and refuses pre-abort before send", async t => { const f=fixture(); t.after(()=>f.dispatcher.dispose()); const signal=signalModel(); signal.abort(); const invalid=await observed(f.dispatcher.dispatch("",{})), aborted=await observed(f.dispatcher.dispatch("work",{},{signal})); assert.equal(invalid.code==="invalid_request"&&aborted.code==="request_aborted"&&f.transport.sent().length===0,true); });
test("INITIAL O2 correlates reversed replies to owning callers", async t => { const f=fixture(); t.after(()=>f.dispatcher.dispose()); const promises=[1,2,3].map(value=>observed(f.dispatcher.dispatch("work",{value}))); for(const id of [3,1,2]) f.transport.emitMessage({type:"work.completed",requestId:`r${id}`,result:id*10}); f.timers.fireAll(); const results=await Promise.all(promises); assert.equal(results.every((r,i)=>r.resolved&&r.value===(i+1)*10),true); });
test("INITIAL O3 maps remote and send failure codes", async t => { const remote=fixture(), send=fixture({transport:createFakeTransport({onSend(){throw new Error("private transport detail");}})}); t.after(()=>{remote.dispatcher.dispose();send.dispatcher.dispose();}); const response=observed(remote.dispatcher.dispatch("work",{})); remote.transport.emitMessage({type:"work.failed",requestId:"r1",error:"private detail"}); remote.timers.fireAll(); const a=await response,b=await observed(send.dispatcher.dispatch("work",{})); assert.equal(a.code==="remote_failure"&&b.code==="send_failed",true); });
test("INITIAL O4 owns timeout and abort terminal outcomes", async t => { const f=fixture(); t.after(()=>f.dispatcher.dispose()); const timed=observed(f.dispatcher.dispatch("work",{})); f.timers.fireAll(); const a=await timed; const signal=signalModel(), cancelled=observed(f.dispatcher.dispatch("work",{},{signal})); signal.abort(); f.timers.fireAll(); const b=await cancelled; assert.equal(a.code==="request_timeout"&&b.code==="request_aborted"&&f.dispatcher.pendingCount===0&&signal.listenerCount===0,true); });
test("INITIAL O5 close and disposal reject their pending owners", async t => { const a=fixture(),b=fixture(); t.after(()=>{a.dispatcher.dispose();b.dispatcher.dispose();}); const closing=observed(a.dispatcher.dispatch("work",{})),disposing=observed(b.dispatcher.dispatch("work",{})); a.transport.emitClose(); b.dispatcher.dispose(); a.timers.fireAll(); b.timers.fireAll(); const x=await closing,y=await disposing; assert.equal(x.code==="transport_closed"&&y.code==="dispatcher_disposed",true); });
