import React, { useState } from "react";

// Preserved generated evidence: complete behavior, intentionally oversized ownership.
export default function OversizedWorkshopDashboard({ initialWorkshops, createRegistrationId }) {
  const [workshops, setWorkshops] = useState(() => structuredClone(initialWorkshops)); const [selectedId, setSelectedId] = useState(initialWorkshops[0].id); const [filter, setFilter] = useState(""); const [name, setName] = useState(""); const [seats, setSeats] = useState("1"); const [error, setError] = useState("");
  const filtered = workshops.filter((workshop) => workshop.title.toLowerCase().includes(filter.toLowerCase())); const selected = workshops.find((workshop) => workshop.id === selectedId); const usedSeats = selected.registrations.reduce((sum, registration) => sum + registration.seats, 0);
  const changeFilter = (value) => { setFilter(value); const matches = workshops.filter((workshop) => workshop.title.toLowerCase().includes(value.toLowerCase())); if (matches.length && !matches.some((workshop) => workshop.id === selectedId)) setSelectedId(matches[0].id); };
  const submit = (event) => { event.preventDefault(); const normalized = name.trim(); const count = Number(seats); if (!normalized || !Number.isInteger(count) || count < 1) return setError("Enter a name and a valid seat count."); if (count > selected.capacity - usedSeats) return setError("Not enough seats remaining."); const registration = { id: createRegistrationId(), name: normalized, seats: count }; setWorkshops((current) => current.map((workshop) => workshop.id === selectedId ? { ...workshop, registrations: [...workshop.registrations, registration] } : workshop)); setName(""); setSeats("1"); setError(""); };
  const remove = (id) => setWorkshops((current) => current.map((workshop) => workshop.id === selectedId ? { ...workshop, registrations: workshop.registrations.filter((registration) => registration.id !== id) } : workshop));
  return <main><h1>Workshop dashboard</h1><section aria-label="Workshop selection"><label htmlFor="workshop-filter">Filter workshops</label><input id="workshop-filter" value={filter} onChange={(event) => changeFilter(event.target.value)} /><label htmlFor="workshop">Workshop</label><select id="workshop" value={selectedId} onChange={(event) => setSelectedId(event.target.value)}>{filtered.map((workshop) => <option key={workshop.id} value={workshop.id}>{workshop.title}</option>)}</select></section>{filtered.length === 0 ? <p role="status">No workshops match.</p> : <><h2>{selected.title}</h2><p role="status">{usedSeats} of {selected.capacity} seats used; {selected.capacity - usedSeats} remaining.</p><form onSubmit={submit}><h2>Add registration</h2><label htmlFor="attendee-name">Attendee name</label><input id="attendee-name" value={name} onChange={(event) => setName(event.target.value)} /><label htmlFor="seat-count">Seats</label><input id="seat-count" type="number" min="1" value={seats} onChange={(event) => setSeats(event.target.value)} /><button type="submit">Register attendee</button>{error && <p role="alert">{error}</p>}</form><section><h2>Attendees</h2>{selected.registrations.length === 0 ? <p>No registrations yet.</p> : <table><thead><tr><th>Name</th><th>Seats</th><th>Action</th></tr></thead><tbody>{selected.registrations.map((registration) => <tr key={registration.id}><th scope="row">{registration.name}</th><td>{registration.seats}</td><td><button type="button" onClick={() => remove(registration.id)} aria-label={`Remove ${registration.name}`}>Remove</button></td></tr>)}</tbody></table>}</section></>}</main>;
}
