import assert from "node:assert/strict";
import { test } from "node:test";
import { cookiePair, fixture, json, withApp } from "./helpers.js";

test("validation and equivalent credential denial create no session", async () => { const calls = []; const base = fixture(); const verifier = { dummyRecord: base.passwordVerifier.dummyRecord, async verify(password, record) { calls.push({ password, salt: record.salt }); return base.passwordVerifier.verify(password, record); } }; const testFixture = fixture({ passwordVerifier: verifier }); await withApp(testFixture.app, async (url) => { assert.equal((await fetch(`${url}/api/session`, json({ email: "x" }))).status, 400); for (const body of [{ email: "missing@example.test", password: "wrong" }, { email: "ada@example.test", password: "wrong" }]) { const response = await fetch(`${url}/api/session`, json(body)); assert.equal(response.status, 401); assert.deepEqual(await response.json(), { error: { code: "invalid_credentials", message: "Invalid email or password" } }); } }); assert.equal(calls.length, 2); assert.deepEqual(calls.map(({ salt }) => salt), ["dummy-salt-01", "user-salt-01"]); assert.equal(testFixture.sessions.size, 0); });
test("successful login sets opaque cookie and protects public current user", async () => { const testFixture = fixture(); await withApp(testFixture.app, async (url) => { const login = await fetch(`${url}/api/session`, json({ email: " ADA@EXAMPLE.TEST ", password: "correct horse" })); assert.equal(login.status, 200); assert.deepEqual(await login.json(), { data: { id: "u1", email: "ada@example.test", displayName: "Ada" } }); const setCookie = login.headers.get("set-cookie"); assert.match(setCookie, /HttpOnly/); assert.match(setCookie, /SameSite=Lax/); assert.doesNotMatch(setCookie, /ada|u1|correct|password/i); const me = await fetch(`${url}/api/me`, { headers: { cookie: cookiePair(login) } }); assert.deepEqual(await me.json(), { data: { id: "u1", email: "ada@example.test", displayName: "Ada" } }); }); });
test("login rotates presented session and logout clears and invalidates", async () => { let byte = 1; const testFixture = fixture({ randomBytes: () => Buffer.alloc(32, byte++) }); await withApp(testFixture.app, async (url) => { const first = await fetch(`${url}/api/session`, json({ email: "ada@example.test", password: "correct horse" })); const oldCookie = cookiePair(first); const second = await fetch(`${url}/api/session`, json({ email: "ada@example.test", password: "correct horse" }, { cookie: oldCookie })); const currentCookie = cookiePair(second); assert.notEqual(currentCookie, oldCookie); assert.equal((await fetch(`${url}/api/me`, { headers: { cookie: oldCookie } })).status, 401); const logout = await fetch(`${url}/api/session`, { method: "DELETE", headers: { cookie: currentCookie } }); assert.equal(logout.status, 204); assert.match(logout.headers.get("set-cookie"), /Max-Age=0/); assert.equal((await fetch(`${url}/api/me`, { headers: { cookie: currentCookie } })).status, 401); }); });
test("missing and expired sessions return the same stable denial", async () => { let now = 0; const testFixture = fixture({ clock: { now: () => now }, ttlMs: 10 }); await withApp(testFixture.app, async (url) => { const absent = await fetch(`${url}/api/me`); const login = await fetch(`${url}/api/session`, json({ email: "ada@example.test", password: "correct horse" })); now = 11; const expired = await fetch(`${url}/api/me`, { headers: { cookie: cookiePair(login) } }); assert.equal(absent.status, 401); assert.equal(expired.status, 401); assert.deepEqual(await absent.json(), await expired.json()); }); });
test("production cookie and forwarded dependency failures are sanitized", async () => { const secure = fixture({ production: true }); await withApp(secure.app, async (url) => { const login = await fetch(`${url}/api/session`, json({ email: "ada@example.test", password: "correct horse" }, { origin: "https://course.example", "x-forwarded-proto": "https" })); assert.match(login.headers.get("set-cookie"), /Secure/); }); const users = { ...secure.users, async findByEmail() { throw new Error("database secret path"); } }; const failed = fixture({ users }); await withApp(failed.app, async (url) => { const response = await fetch(`${url}/api/session`, json({ email: "ada@example.test", password: "correct horse" })); assert.equal(response.status, 500); assert.doesNotMatch(await response.text(), /database|secret|path|stack/i); }); });
