import assert from "node:assert/strict";
import test from "node:test";
import { readFileSync } from "node:fs";
function freeze(value){if(value&&typeof value==="object"){Object.values(value).forEach(freeze);Object.freeze(value);}return value;}
const cases=JSON.parse(readFileSync(new URL("../support/cases.json",import.meta.url)));
import { recipientKey } from "../student/p01.mjs";
test("P01: classroom contract and input immutability", () => { const c=cases[0]; for(let i=0;i<c.inputs.length;i++){ const input=structuredClone(c.inputs[i]); const before=structuredClone(input); assert.deepEqual(recipientKey(input),c.expected[i], `${c.project_id} case ${i+1}`); assert.deepEqual(input,before,"inputs remain unchanged"); const frozen=freeze(structuredClone(c.inputs[i])); assert.deepEqual(recipientKey(frozen),c.expected[i],"frozen finite contract input"); } });
import { jobTransition } from "../student/p02.mjs";
test("P02: classroom contract and input immutability", () => { const c=cases[1]; for(let i=0;i<c.inputs.length;i++){ const input=structuredClone(c.inputs[i]); const before=structuredClone(input); assert.deepEqual(jobTransition(input),c.expected[i], `${c.project_id} case ${i+1}`); assert.deepEqual(input,before,"inputs remain unchanged"); const frozen=freeze(structuredClone(c.inputs[i])); assert.deepEqual(jobTransition(frozen),c.expected[i],"frozen finite contract input"); } for(const value of [NaN,Infinity,-Infinity]){const input=freeze({state:{status:"active",progress:65,reportId:"kept"},event:{type:"progress",progress:value}});assert.deepEqual(jobTransition(input),input.state,"non-finite progress refused");} });
import { settleOwned } from "../student/p03.mjs";
test("P03: classroom contract and input immutability", () => { const c=cases[2]; for(let i=0;i<c.inputs.length;i++){ const input=structuredClone(c.inputs[i]); const before=structuredClone(input); assert.deepEqual(settleOwned(input),c.expected[i], `${c.project_id} case ${i+1}`); assert.deepEqual(input,before,"inputs remain unchanged"); const frozen=freeze(structuredClone(c.inputs[i])); assert.deepEqual(settleOwned(frozen),c.expected[i],"frozen finite contract input"); } const firstInput={pending:[{id:"A",type:"calculate"},{id:"B",type:"export"}],reply:{requestId:"B",type:"export.completed",result:false}};const before=structuredClone(firstInput);const first=settleOwned(freeze(firstInput));assert.deepEqual(first,{pending:[{id:"A",type:"calculate"}],settled:{id:"B",result:false}},"first current completion");assert.deepEqual(firstInput,before,"first replay input unchanged");const next=freeze({pending:first.pending,reply:firstInput.reply});const nextBefore=structuredClone(next);assert.deepEqual(settleOwned(next),{pending:[{id:"A",type:"calculate"}],settled:null},"replay uses actual returned pending and same reply");assert.deepEqual(next,nextBefore,"replay input unchanged"); });
