(function(root){'use strict';
const fields=s=>s.sections.flatMap(z=>z.fields),plain=x=>x!==null&&typeof x==='object'&&!Array.isArray(x)&&Object.getPrototypeOf(x)===Object.prototype;
function strictJSON(text){let at=0,depth=0;function ws(){while(at<text.length&&/[ \t\r\n]/.test(text[at]))at++;}function val(){ws();if(++depth>80)throw Error('JSON nesting limit');let x;if(text[at]==='{'){at++;x={};const seen=new Set();ws();if(text[at]!=='}')for(;;){const key=str();if(seen.has(key))throw Error('Duplicate JSON key');seen.add(key);ws();if(text[at++]!==':')throw Error('JSON colon');Object.defineProperty(x,key,{value:val(),enumerable:true,writable:true,configurable:true});ws();if(text[at]===','){at++;ws();continue;}break;}if(text[at++]!=='}')throw Error('JSON object');}else if(text[at]==='['){at++;x=[];ws();if(text[at]!==']')for(;;){x.push(val());ws();if(text[at]===','){at++;continue;}break;}if(text[at++]!==']')throw Error('JSON array');}else if(text[at]==='"')x=str();else{const m=/^(?:true|false|null|-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?)/.exec(text.slice(at));if(!m)throw Error('JSON value');at+=m[0].length;x=JSON.parse(m[0]);}depth--;return x;}function str(){ws();if(text[at]!=='"')throw Error('JSON key');const start=at++;while(at<text.length){if(text[at]==='\\'){at+=2;continue;}if(text[at++]==='"')return JSON.parse(text.slice(start,at));}throw Error('JSON string');}const x=val();ws();if(at!==text.length)throw Error('JSON trailing data');return x;}
const reviewIDs=['PROJECT_IDENTITY','LOCKED_INSTALL','DEPENDENCY_AUDIT','PRODUCTION_BUILD','RUNTIME_HEALTH','LOG_REDACTION','CONFIG_SECRETS','HTTP_ERROR_HEADERS','DEPLOYMENT','EXCEPTIONS'];
function reviewRows(text){const lines=text.split(/\r?\n/).filter(x=>x.trim());if(lines.length!==10)throw Error('review_inventory: exactly ten nonblank rows required');const rows=lines.map(line=>{const cells=line.split('|').map(x=>x.trim());if(cells.length!==7||cells.some(x=>!x))throw Error('review_inventory: seven nonblank pipe-separated cells per row');const [id,claim,source,state,owner,nextAction,limit]=cells;if(!reviewIDs.includes(id)||!['pass','fail','unknown'].includes(state))throw Error('review_inventory: exact ID and lower-case state required');return {id,claim,source,state,owner,nextAction,limit};});if(new Set(rows.map(r=>r.id)).size!==10)throw Error('review_inventory: duplicate or missing ID');const required=rows.filter(r=>r.id!=='DEPLOYMENT');return {rows,decision:required.some(r=>r.state==='fail')?'FAIL':required.some(r=>r.state==='unknown')?'UNKNOWN':'PASS',verified:false};}
function defaults(s){return Object.fromEntries(fields(s).map(f=>[f.id,f.default]));}
function shape(v,s){if(!plain(v)||Object.keys(v).length!==fields(s).length)throw Error('Exact values object required');for(const f of fields(s)){const x=v[f.id];if(!Object.hasOwn(v,f.id)||(f.kind==='checkbox'?typeof x!=='boolean':typeof x!=='string'||x.length>f.max||f.options&&!f.options.includes(x)))throw Error('Invalid field '+f.id);}if(Object.keys(v).some(k=>!fields(s).some(f=>f.id===k)))throw Error('Unknown field');}
function pack(v,s){shape(v,s);return {schema:s.schema,version:s.version,savedAt:new Date().toISOString(),values:{...v},provenance:'USER_ENTERED_UNVERIFIED_DRAFT'};}
function importDraft(text,s){if(typeof text!=='string'||new TextEncoder().encode(text).length>2000000)throw Error('Import byte limit');const x=strictJSON(text);if(!plain(x)||Object.keys(x).sort().join(',')!=='provenance,savedAt,schema,values,version'||x.schema!==s.schema||x.version!==s.version||typeof x.provenance!=='string'||typeof x.savedAt!=='string'||!Number.isFinite(Date.parse(x.savedAt))||new Date(x.savedAt).toISOString()!==x.savedAt)throw Error('Import schema/version');shape(x.values,s);return {...x.values,declaration_confirmed:false,pdf_review_status:''};}
function filename(v){const code=String(v.student_code||'').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^A-Za-z0-9-]+/g,'_').replace(/^_+|_+$/g,'').slice(0,50);return code?'TW2026_S14_'+code+'.pdf':null;}
function check(v,s,final=false){const errors=[];try{shape(v,s);}catch(e){return {ok:false,errors:[e.message]};}for(const f of fields(s)){if((final||f.phase==='core')&&f.kind!=='checkbox'&&!v[f.id].trim())errors.push(f.id+': record evidence or an explicit missing witness and limitation');}if(!filename(v))errors.push('student_code: approved code required');if(final){try{const review=reviewRows(v.review_inventory),mapping={LOCKED_INSTALL:'locked_install_state',DEPENDENCY_AUDIT:'dependency_audit_state',PRODUCTION_BUILD:'production_build_state',RUNTIME_HEALTH:'runtime_health_state',LOG_REDACTION:'log_redaction_state',CONFIG_SECRETS:'config_secret_state',HTTP_ERROR_HEADERS:'http_error_header_state'};for(const row of review.rows){const key=mapping[row.id];if(key&&(row.state==='unknown'?!['UNKNOWN','NOT_EXECUTED','BLOCKED_UNQUALIFIED'].includes(v[key]):v[key]!==row.state.toUpperCase()))errors.push(key+': contradicts the review row');}if(review.decision==='FAIL'&&v.review_gate_decision!=='FAIL'||review.decision==='UNKNOWN'&&!['UNKNOWN','HOLD'].includes(v.review_gate_decision)||review.decision==='PASS'&&!['PASS','HOLD'].includes(v.review_gate_decision))errors.push('review_gate_decision: contradicts required review rows');}catch(e){errors.push(e.message);}if(v.declaration_confirmed!==true)errors.push('declaration_confirmed: review truthful redacted evidence first');if(!['FINAL_REVIEWED_READY_NOT_SUBMITTED','SUBMITTED_UNVERIFIED'].includes(v.pdf_review_status))errors.push('pdf_review_status: review the actual saved PDF');}return {ok:errors.length===0,errors,verified:false};}
root.S14Form={fields,defaults,shape,pack,importDraft,filename,check,strictJSON,reviewRows};if(typeof module!=='undefined')module.exports=root.S14Form;
})(globalThis);
