import assert from "node:assert/strict";
import test from "node:test";
import WebSocket from "ws";
import { once } from "node:events";
import { connect, nextMessage, post, withSystem } from "./helpers.js";

test("registration validates protocol, replaces matching identity, and cleans precisely", async () => { await withSystem(async ({ wsUrl, coordinator }) => { const invalid = new WebSocket(`${wsUrl}/replies?session=alice-session`); await once(invalid, "open"); invalid.send("not-json"); const [code] = await once(invalid, "close"); assert.equal(code, 4400); const first = await connect(wsUrl, "alice-session", "browser"); const replaced = once(first.socket, "close"); const second = await connect(wsUrl, "alice-session", "browser"); assert.equal((await replaced)[0], 4401); const other = await connect(wsUrl, "malik-session", "browser"); assert.equal(coordinator.diagnostics().connectionCount, 2); second.socket.close(); await once(second.socket, "close"); assert.equal(coordinator.diagnostics().connectionCount, 1); other.socket.close(); }); });
test("HTTP accepts immediately and correlates isolated out-of-order replies", async () => { const controls = []; let id = 0; await withSystem(async ({ wsUrl, httpUrl, coordinator }) => { const alice = await connect(wsUrl, "alice-session", "a"); const malik = await connect(wsUrl, "malik-session", "m"); const aliceMessage = nextMessage(alice.socket); const malikMessage = nextMessage(malik.socket); const first = await post(httpUrl, "alice-session", { operation: "sum", values: [1, 2], connectionId: "a" }); const second = await post(httpUrl, "malik-session", { operation: "sum", values: [8, 1], connectionId: "m" }); assert.equal(first.status, 202); assert.equal(second.status, 202); assert.match(first.headers.get("location"), /req-1/); assert.equal(coordinator.diagnostics().pendingCount, 2); controls[1].resolve(9); controls[0].resolve(3); assert.deepEqual(await malikMessage, { type: "calculation.completed", requestId: "req-2", result: 9 }); assert.deepEqual(await aliceMessage, { type: "calculation.completed", requestId: "req-1", result: 3 }); assert.equal(coordinator.diagnostics().pendingCount, 0); alice.socket.close(); malik.socket.close(); }, { nextRequestId: () => `req-${++id}`, runCalculation: () => new Promise((resolve, reject) => controls.push({ resolve, reject })) }); });
test("unregistered and cross-principal connection IDs schedule no work", async () => { let calls = 0; await withSystem(async ({ wsUrl, httpUrl }) => { const alice = await connect(wsUrl, "alice-session", "private"); for (const [session, connectionId] of [["alice-session", "missing"], ["malik-session", "private"]]) { const response = await post(httpUrl, session, { operation: "sum", values: [1], connectionId }); assert.equal(response.status, 409); assert.equal((await response.json()).error.code, "reply_connection_required"); } assert.equal(calls, 0); alice.socket.close(); }, { nextRequestId: () => "unused", runCalculation: async () => { calls += 1; return 1; } }); });
test("failure is sanitized and disconnect or duplicate settlement leaves no pending work", async () => { let rejectWork; await withSystem(async ({ wsUrl, httpUrl, coordinator }) => { const client = await connect(wsUrl, "alice-session", "a"); const message = nextMessage(client.socket); assert.equal((await post(httpUrl, "alice-session", { operation: "sum", values: [1], connectionId: "a" })).status, 202); rejectWork(new Error("secret stack detail")); assert.deepEqual(await message, { type: "calculation.failed", requestId: "req", error: { code: "calculation_failed", message: "Calculation failed" } }); assert.equal(coordinator.diagnostics().pendingCount, 0); client.socket.close(); }, { nextRequestId: () => "req", runCalculation: () => new Promise((_resolve, reject) => { rejectWork = reject; }) }); });
test("synchronous scheduling failure is sanitized and instances are isolated", async () => { await withSystem(async ({ wsUrl, httpUrl, coordinator }) => { const client = await connect(wsUrl, "alice-session", "a"); const response = await post(httpUrl, "alice-session", { operation: "sum", values: [1], connectionId: "a" }); assert.equal(response.status, 500); assert.doesNotMatch(await response.text(), /scheduler secret|stack/i); assert.equal(coordinator.diagnostics().pendingCount, 0); client.socket.close(); }, { nextRequestId: () => "req", runCalculation: () => { throw new Error("scheduler secret"); } }); await withSystem(async ({ coordinator }) => assert.deepEqual(coordinator.diagnostics(), { connectionCount: 0, pendingCount: 0 })); });
